### ISSUE TITLE
有测试版的BIOS不知道解决了什么

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#1]
孤独凤凰战士微薄更新了测试BIOS：最新测试版B​​IOS，修复了一些雷电兼容性问题，已将将雷电性能加满，需要按照说明刷入BIOS并启用选项。链接：https ://pan.baidu 。 com / share / init？surl = ZIBQtExk3K4denbU1oo-dQ提取码：hfqk。不知道能否有帮助？

**Comment by hx2nn** [comment]
没有解决转HDMI以及声音外放问题，但解决了电池百分比一直65％的问题，同样有这个问题的小伙伴可以试试。（另，刷后启动项目丢失CLOVER ，需要在CLOVER中重新添加）

**Comment by WangRicky** [comment]
> 孤独凤凰战士微薄更新了测试BIOS：最新测试版B​​IOS，修复了一些雷电兼容性问题，已将将雷电性能加满，需要按照说明刷入BIOS并启用选项。链接：https ://pan.baidu 。 com / share / init？surl = ZIBQtExk3K4denbU1oo-dQ提取码：hfqk。不知道能否有帮助？

这个只是雷电接口的高性能模式，无法解决目前的问题
