### ISSUE TITLE
兄弟你的耳机好用么？

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#10]
我从clover转如oc用你的配置文件，我为啥耳机也没驱动？

**Comment by WangRicky** [comment]
我更新15.3出现了偶尔耳机无声的情况，一般重启一次就好了，15.2没这个问题（无论是clover还是oc都一样）

**Comment by hx2nn** [comment]
是的，和你一样耳机偶尔开机不好用，咱们的仿冒id是31？我在15.2之前都是仿冒11才有声音（不是1F而是0b,不知道为啥）

**Comment by WangRicky** [comment]
> 是的，和你一样耳机偶尔开机不好用，咱们的仿冒id是31？我在15.2之前都是仿冒11才有声音（不是1F而是0b,不知道为啥）

alc285可用的注入id有11，21，31
