### ISSUE TITLE
兄弟你的可以实现手表解锁么

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#12]
我的1820也显示支持，没什么老显示您的Mac无法与Apple Watch通信请确保Apple Watch已解锁、佩戴在腕上且已打开电源。你是怎么做到的

**Comment by WangRicky** [comment]
我

> 我的1820也显示支持，没什么老显示您的Mac无法与Apple Watch通信请确保Apple Watch已解锁、佩戴在腕上且已打开电源。你是怎么做到的

蓝牙WiFi正常这个就是正常的
