### ISSUE TITLE
拆掉981硬盘的话OC要怎么设置？

### ISSUE THREAD

**Issue by Eveningme** [WangRicky/Y9000X-HACKINTOSH#13]
我直接换掉了981硬盘，目前就装着一块Intel的硬盘。
OC里需要怎么设置吗？谢谢了

**Comment by WangRicky** [comment]
> 我直接换掉了981硬盘，目前就装着一块Intel的硬盘。
> OC里需要怎么设置吗？谢谢了

停用SSDT-DNVMe.aml即可
