### ISSUE TITLE
兄弟，用了最新的efi，重启找不到mac盘符了，你上传的对不？

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#16]
现在只能u用clover盘启动了。显示错误bs:failed to locate valld opencore image -01
failed to load poencore from disk - found

**Comment by WangRicky** [comment]
注意替换boot文件夹里的bootx64.efi

**Comment by WangRicky** [comment]
> 现在只能u用clover盘启动了。显示错误bs:failed to locate valld opencore image -01
> failed to load poencore from disk - found

注意替换boot文件夹里的bootx64.efi

**Comment by hx2nn** [comment]
我是用你的efi所有文件进行替换的

**Comment by WangRicky** [comment]
> 我是用你的efi所有文件进行替换的

我已经比对过了，完全一致

**Comment by hx2nn** [comment]
好用了，貌似因为彻底删除了efi分区的文件，影响了识别
