### ISSUE TITLE
您好

### ISSUE THREAD

**Issue by ghost** [WangRicky/Y9000X-HACKINTOSH#17]
我是Y9000X 双硬盘双系统，想请教一下您怎么弄的双硬盘切换，可否加一下您的qq

**Comment by WangRicky** [comment]
> 我是Y9000X 双硬盘双系统，想请教一下您怎么弄的双硬盘切换，可否加一下您的qq

开机F12，日常几乎不开win

**Comment by ghost** [comment]
那我可以用OCC什么版本来编辑您的引导呢~

**Comment by ghost** [comment]
您好，在您工作繁忙之际还打扰您~我成功引导进入了系统，目前出现了1820a蓝牙无法使用和开机之后屏幕亮度很暗

**Comment by WangRicky** [comment]
> 您好，在您工作繁忙之际还打扰您~我成功引导进入了系统，目前出现了1820a蓝牙无法使用和开机之后屏幕亮度很暗

我不推荐使用OCC编辑，屏幕很暗应该和使用occ编辑，破坏了配置文件结构有关，蓝牙无法使用可能是驱动加载不正常，重启再试

**Comment by ghost** [comment]
好的，我OCC编辑过的文件给删除了，您能否帮我看看下在哪来设置开机等待10秒钟

**Comment by ghost** [comment]
您好我尝试无无编译，还是会遇到开机在读取条的时候，屏幕亮度很低~开机之后大概五分钟左右屏幕才会正常

**Comment by WangRicky** [comment]
> 您好我尝试无无编译，还是会遇到开机在读取条的时候，屏幕亮度很低~开机之后大概五分钟左右屏幕才会正常

印象中远景有类似帖子，你查一下，和配置文件没关系

**Comment by rong-lilith** [comment]
我想问一下大佬，那个关于雷电的接口修复的文章有没有啊~求教

**Comment by WangRicky** [comment]
> 您好我尝试无无编译，还是会遇到开机在读取条的时候，屏幕亮度很低~开机之后大概五分钟左右屏幕才会正常

开机黑屏请检查三码是否填写
