### ISSUE TITLE
您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗

### ISSUE THREAD

**Issue by wuweijavadeveloper** [WangRicky/Y9000X-HACKINTOSH#18]
您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗

**Comment by daya-prac** [comment]
蓝牙也没问题？

**Comment by WangRicky** [comment]
> 您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗

触控板有一定概率会无法使用，重启即可，原因我现在也没找到

**Comment by wuweijavadeveloper** [comment]
> 蓝牙也没问题？

妙控板和airpod都正常使用，暂时没发现问题

**Comment by wuweijavadeveloper** [comment]
> > 您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗
> 
> 触控板有一定概率会无法使用，重启即可，原因我现在也没找到

我是重启了一次也还是不能用，不过幸好之前买了妙控板- -虽然相比原生触摸板有点延迟，但也还不错

**Comment by WangRicky** [comment]
> > > 您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗
> > 
> > 
> > 触控板有一定概率会无法使用，重启即可，原因我现在也没找到
> 
> 我是重启了一次也还是不能用，不过幸好之前买了妙控板- -虽然相比原生触摸板有点延迟，但也还不错

刚发现我的也没法用，检查了一下，发现触控板驱动更新了，已上传

**Comment by wuweijavadeveloper** [comment]
> > > > 您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗
> > > 
> > > 
> > > 触控板有一定概率会无法使用，重启即可，原因我现在也没找到
> > 
> > 
> > 我是重启了一次也还是不能用，不过幸好之前买了妙控板- -虽然相比原生触摸板有点延迟，但也还不错
> 
> 刚发现我的也没法用，检查了一下，发现触控板驱动更新了，已上传

我刚更换了您新上传的两个I2C文件，重启了还是没法用触摸板- -头疼

**Comment by wuweijavadeveloper** [comment]
> > > > 您好，用了您的oc启动，其他都完美，就触摸板不能使用，请问有什么解决办法可以参考吗
> > > 
> > > 
> > > 触控板有一定概率会无法使用，重启即可，原因我现在也没找到
> > 
> > 
> > 我是重启了一次也还是不能用，不过幸好之前买了妙控板- -虽然相比原生触摸板有点延迟，但也还不错
> 
> 刚发现我的也没法用，检查了一下，发现触控板驱动更新了，已上传

看了下驱动加载，com.alexandred.VoodooI2CHID (1)驱动版本是1，com.alexandred.VoodooI2C (2.4) 是2.4，会不会是前一个版本有点旧？

**Comment by fireicewater** [comment]
我刚刚更新了最新的efi,和15.4补充更新,触摸板还是无法启动

**Comment by fireicewater** [comment]
> 我刚刚更新了最新的efi,和15.4补充更新,触摸板还是无法启动

刚把I2C 更换为2.3版本,触摸板现在能驱动了

2.4 版本看远景论坛上似乎有解决方案,没号看不了,有号的话看一下是否能调整
https://bbs.pcbeta.org/viewthread-1852478-1-1.html

**Comment by wuweijavadeveloper** [comment]
> > 我刚刚更新了最新的efi,和15.4补充更新,触摸板还是无法启动
> 
> 刚把I2C 更换为2.3版本,触摸板现在能驱动了
> 
> 2.4 版本看远景论坛上似乎有解决方案,没号看不了,有号的话看一下是否能调整
> https://bbs.pcbeta.org/viewthread-1852478-1-1.html

这个efi上个版本也是2.3，我用那个也不能驱动触摸板。。。

**Comment by fireicewater** [comment]
> > > 我刚刚更新了最新的efi,和15.4补充更新,触摸板还是无法启动
> > 
> > 
> > 刚把I2C 更换为2.3版本,触摸板现在能驱动了
> > 2.4 版本看远景论坛上似乎有解决方案,没号看不了,有号的话看一下是否能调整
> > https://bbs.pcbeta.org/viewthread-1852478-1-1.html
> 
> 这个efi上个版本也是2.3，我用那个也不能驱动触摸板。。。

我按照上面帖子更换了一下注入顺序看看是不是这个原因

GPIO
I2CServices
I2C
I2CHID

**Comment by WangRicky** [comment]
@wuweijavadeveloper @fireicewater  已回退驱动，本机测试正常

**Comment by wuweijavadeveloper** [comment]
> > > > 我刚刚更新了最新的efi,和15.4补充更新,触摸板还是无法启动
> > > 
> > > 
> > > 刚把I2C 更换为2.3版本,触摸板现在能驱动了
> > > 2.4 版本看远景论坛上似乎有解决方案,没号看不了,有号的话看一下是否能调整
> > > https://bbs.pcbeta.org/viewthread-1852478-1-1.html
> > 
> > 
> > 这个efi上个版本也是2.3，我用那个也不能驱动触摸板。。。
> 
> 我按照上面帖子更换了一下注入顺序看看是不是这个原因
> 
> GPIO
> I2CServices
> I2C
> I2CHID

我解决了，一开始只改顺序还是不行，用2.3的I2C驱动，然后把I2CHID换成2.4（此EFI昨天那个版本，也就是目前仓库的I2CHID和I2C同时使用不行），触摸板就可以用了

**Comment by wuweijavadeveloper** [comment]
> @wuweijavadeveloper @fireicewater 已回退驱动，本机测试正常

感谢大佬，目前已正常使用触摸板~用2.3的I2C驱动，然后把I2CHID换成2.4（此EFI昨天那个版本，也就是目前仓库的I2CHID和I2C同时使用不行），触摸板就可以用了
