### ISSUE TITLE
睡眠后偶尔无法唤醒且风扇狂赚，百度了下发现白果也有这个问题

### ISSUE THREAD

**Issue by wuweijavadeveloper** [WangRicky/Y9000X-HACKINTOSH#19]
大家有遇到吗？

**Comment by WLeGeQ** [comment]
还没买笔记本

**Comment by deamonssouls** [comment]
我的无法唤醒？是不是做了什么调整?

**Comment by HiramChen-CN** [comment]
> 还没买笔记本

再忍忍。2020就快出了

**Comment by wqrqwerqrw** [comment]
风扇的问题升级到最新的bios就能解决了吧，虽然会有些代价

至于睡眠的问题我是把关于显卡的补丁删掉后修复的

**Comment by wuweijavadeveloper** [comment]
> 风扇的问题升级到最新的bios就能解决了吧，虽然会有些代价
> 
> 至于睡眠的问题我是把关于显卡的补丁删掉后修复的

可以指导下具体是哪个补丁吗？大概一周会睡死三次，每次都得重启还是有点麻烦

**Comment by wqrqwerqrw** [comment]
> > 风扇的问题升级到最新的bios就能解决了吧，虽然会有些代价
> > 至于睡眠的问题我是把关于显卡的补丁删掉后修复的
> 
> 可以指导下具体是哪个补丁吗？大概一周会睡死三次，每次都得重启还是有点麻烦

## 我是i7+16+FHD版本的 其他版本不知道， 我删除了这个补丁
另外我之前的情况是睡眠后100%无法正常启动，表现为声音正常，屏幕有背光但是黑屏，和你的情况貌似不太一样
<img width="1440" alt="截屏2020-04-20 08 57 52" src="https://user-images.githubusercontent.com/42306566/79704703-3403b000-82e5-11ea-8ddb-f49b9d2415d0.png">
## 关于显卡的这个 另外我还根据 [这条issue](https://github.com/WangRicky/Y9000X-HACKINTOSH/issues/4) 另外添加了两个, 但我不确定跟这个有没有关系
<img width="947" alt="截屏2020-04-20 09 01 32" src="https://user-images.githubusercontent.com/42306566/79704790-aa081700-82e5-11ea-96a8-06705f9e4239.png">
<img width="973" alt="截屏2020-04-20 09 06 25" src="https://user-images.githubusercontent.com/42306566/79704913-3b778900-82e6-11ea-9cda-c9a97f155500.png">

**Comment by deamonssouls** [comment]
@wqrqwerqrw  删除是指删除掉整个设备`PciRoot(0x0)/Pci(0x2,0x0)`，还是删除model这个键？

另外显卡添加了两个设备？看图应该是指`PciRoot(0x0)/Pci(0x14,0x0)`、`PciRoot(0x0)/Pci(0x14,0x0)`。然后`PciRoot(0x0)/Pci(0x0,0x0)`是新增的？

**Comment by gwjtssy** [comment]
删掉整个设备PciRoot(0x0)/Pci(0x2,0x0)
