### ISSUE TITLE
我得触摸板基本可以使用，需要更新你得EFI么？

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#2]
触摸板基本上可以用，但是切换程序，四指未启动，你得能达到什么效果。如果我要更新如何操作啊？加油

**Comment by WangRicky** [comment]
> 触摸板基本上可以用，但是切换程序，四指未启动，你得能达到什么效果。如果我要更新如何操作啊？加油

不需要替换，只是之前的文件有问题，调整了一下，只要在触控板设置中看到多指的那些选项就可以了
