### ISSUE TITLE
你好，开机后会黑屏一段时间，但系统是正常运行的，可以听到声音，几分钟后亮屏恢复正常

### ISSUE THREAD

**Issue by PatrickRunti** [WangRicky/Y9000X-HACKINTOSH#20]
你好，非常感谢你完善此efi，这个efi是我试过最接近完美的，我的是i7，fhd，已经试了好几个efi了，有些触摸板用不了，有些安装到一半panic，有些安装好后雷电插东西没反应。这一个用的open core装上后唯一的问题就是黑屏，1，开机在白苹果进度条到一半的时候，屏幕一闪就黑屏，按键盘时可以听到反馈声音，但屏幕是纯黑不背光，过几分钟后亮屏正常，但有小几率情况会不黑屏，正常直接进入系统。2，用雷电口外接显示器时黑屏，外接的显示器有显示画面，但内置显示器黑屏，有背光，并且在尝试将外界显示器拔掉后依旧不能亮屏。3，合上盖子之后黑屏，有背光，不管按如何键都无法唤醒，只能强制重启。
不知道导致这些问题的是什么原因，我已经研究了好几天了无法解决，所以来这里求助，谢谢。

**Comment by wqrqwerqrw** [comment]
fhd可以试试把核显的补丁删掉
<img width="1440" alt="截屏2020-04-20 08 57 52" src="https://user-images.githubusercontent.com/42306566/79704703-3403b000-82e5-11ea-8ddb-f49b9d2415d0.png">

**Comment by HiramChen-CN** [comment]
我4K屏在开机的时候也会闪烁黑屏一下(进度条大约60%的样子)，大约2秒后恢复，每次开机都这样，有解决办法么

**Comment by PatrickRunti** [comment]
> fhd可以试试把核显的补丁删掉
> <img alt="截屏2020-04-20 08 57 52" width="1440" src="https://user-images.githubusercontent.com/42306566/79704703-3403b000-82e5-11ea-8ddb-f49b9d2415d0.png">
非常感谢你的回复🙏，我现在用了另一个efi，用clover引导安装了，上述的问题全都解决了，已经非常接近完美黑苹果了，但现在唯一的问题就是：开机使用后有一定几率毫无征兆的死机，冻屏，什么也动不了，风扇开始狂转，只能强制重启来解决问题。但也有几率完全正常，连续使用几小时也正常。不知道要怎么解决。

**Comment by xuejinwei** [comment]
@PatrickRunti  你现在用的那个EFI 了，我也遇到了和你一样，开机后黑屏的情况了

**Comment by xia120bo** [comment]
很赞。已经完美解决唤醒黑屏问题。用了好几天。一切正常。

**Comment by HuangDouMianJiang** [comment]
我这边其他都挺正常的，就是刚开机的时候屏幕特别暗，大概就是显示亮度的 15%左右

**Comment by gwjtssy** [comment]
> 很赞。已经完美解决唤醒黑屏问题。用了好几天。一切正常。

如何解决的？

**Comment by WangRicky** [comment]
> 我4K屏在开机的时候也会闪烁黑屏一下(进度条大约60%的样子)，大约2秒后恢复，每次开机都这样，有解决办法么

开机屏幕闪烁是系统加载显卡驱动造成的，属于正常现象，只有独显才有可能解决此问题

**Comment by WangRicky** [comment]
> @PatrickRunti 你现在用的那个EFI 了，我也遇到了和你一样，开机后黑屏的情况了

开机黑屏请检查三码是否填写

**Comment by WangRicky** [comment]
> > 很赞。已经完美解决唤醒黑屏问题。用了好几天。一切正常。
> 
> 如何解决的？

开机黑屏请检查三码是否填写
