### ISSUE TITLE
休眠唤醒之后耳机一定概率不可用

### ISSUE THREAD

**Issue by HiramChen-CN** [WangRicky/Y9000X-HACKINTOSH#22]
开机的时候是好的，不插耳机声音可以调节，只是没声音而已，但是休眠几次之后，声音设备列表就变为空的了，声音也不可以调节，插耳机也没声音，必需要重启才能解决，大神有办法优化么

![image](https://user-images.githubusercontent.com/12631466/81363472-fb057100-9115-11ea-8b2c-1011ff160ce8.png)

插入耳机时的声音设备列表
![image](https://user-images.githubusercontent.com/12631466/81363681-82eb7b00-9116-11ea-83f8-aebd4779d294.png)

**Comment by wqrqwerqrw** [comment]
请问解决了吗
我也有类似的问题
我的情况是 : 
声音可用, 但是只有单声道, 并且音乐里的人声(或者说某一段频率的声音)会被消除掉

有时候可以通过`sudo killall coreaudiod`解决, 不过大概率不行

**Comment by Corazon0513** [comment]
我的设备更惨， 接耳机随机出声，还没找到原因。

**Comment by HiramChen-CN** [comment]
> 请问解决了吗
> 我也有类似的问题
> 我的情况是 :
> 声音可用, 但是只有单声道, 并且音乐里的人声(或者说某一段频率的声音)会被消除掉
> 
> 有时候可以通过`sudo killall coreaudiod`解决, 不过大概率不行

你的是通过雷电口出来的USB声道？我用的耳麦孔，没出现单声道或者某频段丢失的问题。
更新了延迟加载声卡驱动的版本后暂时没出现这个问题，等稳定几天就关issue了。

**Comment by HiramChen-CN** [comment]
> 我的设备更惨， 接耳机随机出声，还没找到原因。

是随机破音么？诶，感觉Y9000X 2020版本就是拿来喂小白鼠的，感觉产品有设计缺陷

**Comment by Corazon0513** [comment]
> > 我的设备更惨， 接耳机随机出声，还没找到原因。
> 
> 是随机破音么？诶，感觉Y9000X 2020版本就是拿来喂小白鼠的，感觉产品有设计缺陷

是开机后 有没有声音全靠缘分😂

**Comment by HiramChen-CN** [comment]
> > > 我的设备更惨， 接耳机随机出声，还没找到原因。
> > 
> > 
> > 是随机破音么？诶，感觉Y9000X 2020版本就是拿来喂小白鼠的，感觉产品有设计缺陷
> 
> 是开机后 有没有声音全靠缘分😂

跟我之前一样，开机/休眠之后有没有声音也是看缘分，更新了最新的延迟加载声卡驱动的EFI就好了，暂时每次开机都有声音

**Comment by Corazon0513** [comment]
> > > > 我的设备更惨， 接耳机随机出声，还没找到原因。
> > > 
> > > 
> > > 是随机破音么？诶，感觉Y9000X 2020版本就是拿来喂小白鼠的，感觉产品有设计缺陷
> > 
> > 
> > 是开机后 有没有声音全靠缘分😂
> 
> 跟我之前一样，开机/休眠之后有没有声音也是看缘分，更新了最新的延迟加载声卡驱动的EFI就好了，暂时每次开机都有声音

我也是延迟加载， 目前是小概率开机没声儿， 而且开机的时候会爆音。 不过平常都是用AirPods倒也无所谓了。
