### ISSUE TITLE
开机有时丢失声卡，触摸板也失效

### ISSUE THREAD

**Issue by kuguadashi** [WangRicky/Y9000X-HACKINTOSH#25]
开机大概率出现声卡和触摸板不可用，bios版本21

**Comment by WangRicky** [comment]
> 开机大概率出现声卡和触摸板不可用，bios版本21

已添加声卡驱动延迟加载启动参数，个人已测试2周，加上后未出现声卡不可用问题，你可以试试，触摸板请尝试更新最新的voodooi2c驱动
