### ISSUE TITLE
触摸板使用一段时间后失效

### ISSUE THREAD

**Issue by Corazon0513** [WangRicky/Y9000X-HACKINTOSH#26]
在10.15.3 + OC0.5.7 与 10.15.5 + OC0.5.8下都有此问题

**Comment by HiramChen-CN** [comment]
我觉得极有可能是触摸板手势软件导致的，我用的触摸板驱动更新后的版本，触摸板没啥问题，可以把软件列表发出来，看看是不是软件的问题

**Comment by Corazon0513** [comment]
> 我觉得极有可能是触摸板手势软件导致的，我用的触摸板驱动更新后的版本，触摸板没啥问题，可以把软件列表发出来，看看是不是软件的问题

您好， 触摸板手势软件是单独的软件吗？ 我印象中好像是触摸板驱动自带的功能， 我现在使用的是最新的EFI，并且之后手动更新了macOS10.15.5和OC0.5.8。 软件列表是指启动器内所有的软件吗？

**Comment by WangRicky** [comment]
> 在10.15.3 + OC0.5.7 与 10.15.5 + OC0.5.8下都有此问题

个人更新了10.15.5，oc还是使用0.5.7，没碰到上述问题。

**Comment by HiramChen-CN** [comment]
> > 我觉得极有可能是触摸板手势软件导致的，我用的触摸板驱动更新后的版本，触摸板没啥问题，可以把软件列表发出来，看看是不是软件的问题
> 
> 您好， 触摸板手势软件是单独的软件吗？ 我印象中好像是触摸板驱动自带的功能， 我现在使用的是最新的EFI，并且之后手动更新了macOS10.15.5和OC0.5.8。 软件列表是指启动器内所有的软件吗？

系统自带有部分手势，然后就是第三方软件也可能会有配置手势，可以看看软件列表清单，在/Application目录下，打开终端，然后`ls -l /Application`

我的10.15.5+OC0.5.8没问题

**Comment by liminghao1630** [comment]
我之前也有这个问题，更新了I2C那个ktext之后就没再出现
我的EFI在这里：https://github.com/liminghao1630/Y9000X-1080P-Hackintosh，可以参考

**Comment by Corazon0513** [comment]
> 我之前也有这个问题，更新了I2C那个ktext之后就没再出现
> 我的EFI在这里：[https://github.com/liminghao1630/Y9000X-1080P-Hackintosh，可以参考](https://github.com/liminghao1630/Y9000X-1080P-Hackintosh%EF%BC%8C%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83)

谢谢兄弟 用你的驱动OK了 太感谢！

**Comment by liminghao1630** [comment]
不客气哈哈
