### ISSUE TITLE
USB接入iOS设备无反应

### ISSUE THREAD

**Issue by Corazon0513** [WangRicky/Y9000X-HACKINTOSH#27]
USB接入扩展坞，2.4G接收器都好使。
接入iPad，iPhone后，iOS设备提示充电中， 电脑无反应。

**Comment by WangRicky** [comment]
> USB接入扩展坞，2.4G接收器都好使。
> 接入iPad，iPhone后，iOS设备提示充电中， 电脑无反应。

可以尝试自行定制USB，现在仓库使用的是usbinjectall配合15端口接触补丁的，对于扩展坞USB端口较多的有识别不准确的可能

**Comment by Corazon0513** [comment]
> 可以尝试自行定制USB，现在仓库使用的是usbinjectall配合15端口接触补丁的，对于扩展坞USB端口较多的有识别不准确的可能

好的 我尝试一下 谢谢

**Comment by Corazon0513** [comment]
> 可以尝试自行定制USB，现在仓库使用的是usbinjectall配合15端口接触补丁的，对于扩展坞USB端口较多的有识别不准确的可能

笔记本自带的两个USB-A口也不能正常识别iOS设备 很迷惑

**Comment by Corazon0513** [comment]
没事了 是我不熟悉新macOS的逻辑， 还要在finder里手动信任设备才行。
