### ISSUE TITLE
您好 我用OC引导之后直接就卡在白苹果界面了

### ISSUE THREAD

**Issue by kirkato** [WangRicky/Y9000X-HACKINTOSH#29]
固件用的是黑果小兵的三分去CLOVER+OC+WEPE 然后不管是把OC引导盘里面的BOOT或EFI整体换掉还是只换EFI进OC引导都是卡在白苹果 然后电脑过一会儿就自动关机了 我没有解锁bios所以我在Win10里用写字板把你说的那几项改成了true但是还是进不去 请问可能知道是什么原因吗

**Comment by HuangDouMianJiang** [comment]
> 固件用的是黑果小兵的三分去CLOVER+OC+WEPE 然后不管是把OC引导盘里面的BOOT或EFI整体换掉还是只换EFI进OC引导都是卡在白苹果 然后电脑过一会儿就自动关机了 我没有解锁bios所以我在Win10里用写字板把你说的那几项改成了true但是还是进不去 请问可能知道是什么原因吗

建议使用老版本，目前我这也遇到了这个问题。

**Comment by kirkato** [comment]
> > 固件用的是黑果小兵的三分去CLOVER+OC+WEPE 然后不管是把OC引导盘里面的BOOT或EFI整体换掉还是只换EFI进OC引导都是卡在白苹果 然后电脑过一会儿就自动关机了 我没有解锁bios所以我在Win10里用写字板把你说的那几项改成了true但是还是进不去 请问可能知道是什么原因吗
> 
> 建议使用老版本，目前我这也遇到了这个问题。

谢谢 我将EFI改成了Github Goofysun的就一次进了 我是小白 想问问是不是进去之后还要下个OpenCoreConfigurator来调试黑苹果呢 以及我需不需要再用HackinTool弄一下USB？

**Comment by Orion-sky** [comment]
> > > 固件用的是黑果小兵的三分去CLOVER+OC+WEPE 然后不管是把OC引导盘里面的BOOT或EFI整体换掉还是只换EFI进OC引导都是卡在白苹果 然后电脑过一会儿就自动关机了 我没有解锁bios所以我在Win10里用写字板把你说的那几项改成了true但是还是进不去 请问可能知道是什么原因吗
> > 
> > 
> > 建议使用老版本，目前我这也遇到了这个问题。
> 
> 谢谢 我将EFI改成了Github Goofysun的就一次进了 我是小白 想问问是不是进去之后还要下个OpenCoreConfigurator来调试黑苹果呢 以及我需不需要再用HackinTool弄一下USB？

这个问题我找到解决办法了，开启-v后定位到是蓝牙驱动的问题的问题，把蓝牙驱动替换下就行了

**Comment by WangRicky** [comment]
> 固件用的是黑果小兵的三分去CLOVER+OC+WEPE 然后不管是把OC引导盘里面的BOOT或EFI整体换掉还是只换EFI进OC引导都是卡在白苹果 然后电脑过一会儿就自动关机了 我没有解锁bios所以我在Win10里用写字板把你说的那几项改成了true但是还是进不去 请问可能知道是什么原因吗

蓝牙驱动文件升级了，但是配置忘记修改了，目前已修正。
