### ISSUE TITLE
请问你是CLOVER引导么？

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#3]
下载你得EFI后在CLOVER驱动文件中没有触摸的驱动，只在OC中看到
另：雷电网口补丁是哪一个？

**Comment by WangRicky** [comment]
> 下载你得EFI后在CLOVER驱动文件中没有触摸的驱动，只在OC中看到
> 另：雷电网口补丁是哪一个？

是clover引导，触摸板的驱动是voodooI2C和voodooPS2controller
