### ISSUE TITLE
1080P

### ISSUE THREAD

**Issue by songxuekui** [WangRicky/Y9000X-HACKINTOSH#30]
hi 大神，我的是i7 1080p的 需要改什么配置才能使用啊，请教一下

**Comment by liminghao1630** [comment]
用这个然后去掉4K补丁就行

**Comment by kingZER010** [comment]
> 用这个然后去掉4K补丁就行
这个4k补丁怎么去掉啊？

**Comment by zorroye** [comment]
这个4k补丁怎么去掉啊？

**Comment by zorroye** [comment]
我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。

**Comment by jingyu-tong** [comment]
> 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。

我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛

**Comment by current-liu** [comment]
同问4K补丁怎么去

**Comment by yaotutu** [comment]
> 同问4K补丁怎么去

issue里面已经回答过了，仔细翻一下就有了。

**Comment by current-liu** [comment]
> > 同问4K补丁怎么去
> 
> issue里面已经回答过了，仔细翻一下就有了。

thx,找到了

**Comment by zorroye** [comment]
> > 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。
> 
> 我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛

删掉睡眠正常了。
问下，外接显示器，内屏会黑屏，外屏正常，这个是配置问题吗？

**Comment by jingyu-tong** [comment]
> > > 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。
> > 
> > 
> > 我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛
> 
> 删掉睡眠正常了。
> 问下，外接显示器，内屏会黑屏，外屏正常，这个是配置问题吗？

我也有这个问题，我是每次开机，先睡眠，唤醒后再连外接显示器就好了

**Comment by yaotutu** [comment]
> > > > 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。
> > > 
> > > 
> > > 我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛
> > 
> > 
> > 删掉睡眠正常了。
> > 问下，外接显示器，内屏会黑屏，外屏正常，这个是配置问题吗？
> 
> 我也有这个问题，我是每次开机，先睡眠，唤醒后再连外接显示器就好了

一样的 我也有这个问题.先睡眠,在唤醒,链接显示器就好了.

**Comment by zorroye** [comment]
我买绿联的mm139  typec-dp线。所有操作都是黑屏。。 
主控室vl100-Q3 是否是主控问题，联想自带的转接口，先睡眠，后唤醒是可以的。

**Comment by JarvisXWL** [comment]
> > > > 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。
> > > 
> > > 
> > > 我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛
> > 
> > 
> > 删掉睡眠正常了。
> > 问下，外接显示器，内屏会黑屏，外屏正常，这个是配置问题吗？
> 
> 我也有这个问题，我是每次开机，先睡眠，唤醒后再连外接显示器就好了

请问外接显示器现需要“我是每次开机，先睡眠，唤醒后再连外接显示器就好了”最后解决了吗

**Comment by zhouyu74748585** [comment]
> > > > > 我的是1080p的，不删除的话睡眠唤醒就会黑屏，有啥办法解决吗 一定要删掉吗。。。
> > > > 
> > > > 
> > > > 我也是 1080p 的，删掉之后没发现什么问题的好像，你是删掉了有什么问题嘛
> > > 
> > > 
> > > 删掉睡眠正常了。
> > > 问下，外接显示器，内屏会黑屏，外屏正常，这个是配置问题吗？
> > 
> > 
> > 我也有这个问题，我是每次开机，先睡眠，唤醒后再连外接显示器就好了
> 
> 一样的 我也有这个问题.先睡眠,在唤醒,链接显示器就好了.

这样确实可以，终于知道时好时坏得原因了，不过我是typec直出系统识别到显示器，但是外接显示器不亮，现在还有个问题就是显示得dp菊花链不行，第二个显示器提示时序不对
