### ISSUE TITLE
外接显示器建议

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#32]
昨天买了一根type-c 转 dp线，直接连接显示器（之前是倍思扩展坞），测试达到60Hz（之前30Hz）。如果也有需要可以试试

**Comment by WangRicky** [comment]
> 昨天买了一根type-c 转 dp线，直接连接显示器（之前是倍思扩展坞），测试达到60Hz（之前30Hz）。如果也有需要可以试试

很早之前就买了4k显示器,用type-c转dp可以4k@60,还是很感谢你的提醒

**Comment by SheldonPeng** [comment]
请问type-c 转DP连接显示器可以热拔插吗？

**Comment by wqrqwerqrw** [comment]
> 请问type-c 转DP连接显示器可以热拔插吗？

可以

**Comment by zorroye** [comment]
> > 请问type-c 转DP连接显示器可以热拔插吗？
> 
> 可以

外接显示器后，内屏显示正常吗？我的是黑屏

**Comment by EugeneSnikhovskiy** [comment]
@zorroye Hello. I have same problem with black internal screen after connecting external via hdmi. Do you solve problem?
