### ISSUE TITLE
你这款的传感器驱动天生就支持吗？

### ISSUE THREAD

**Issue by dmlzj** [WangRicky/Y9000X-HACKINTOSH#33]
y7000系列放上传感器驱动，还是找不到传感器，很奇怪。。。

**Comment by WangRicky** [comment]
> y7000系列放上传感器驱动，还是找不到传感器，很奇怪。。。

不是的，要放置对应驱动，SMC的驱动个人测试，除了风扇转速，其他都可以显示，不过我怎么看这些，就没放传感器驱动。

**Comment by dmlzj** [comment]
我找到问题了，官方原话：
SMCDumps 包含 SMC 键值描述信息导出文件 ，可通过运行 smcread -s 生成。我们需要更多 SMC 信息导出文件，如有机会请补充。

我的机型是16，2的，需要从白果拿这个信息，然后他们加上才可以。。
