### ISSUE TITLE
用久了没刚开机流畅

### ISSUE THREAD

**Issue by wuweijavadeveloper** [WangRicky/Y9000X-HACKINTOSH#36]
大家有这个体验吗？开机的时候特别流畅，用几天之后 软件比如浏览器滑动会经常掉帧，虽然不至于卡顿，但对比了一下白果，发现还是有差距的，白果就算不关机也一直流畅。可能白果有独显+分辨率低有一定优势，，不过黑果刚开机跟那个流畅度也差不多。
下个电脑就蹲几年后的arm mbp了，现在日常开发都是y9000x黑果也挺爽的，嘿嘿

**Comment by jingyu-tong** [comment]
体验一样，因为开发开的东西太多，习惯性不关机，过几天会觉得鼠标啥的，稍微有点不跟手的感觉，现在一般两三天关一次机了

**Comment by WangRicky** [comment]
> 大家有这个体验吗？开机的时候特别流畅，用几天之后 软件比如浏览器滑动会经常掉帧，虽然不至于卡顿，但对比了一下白果，发现还是有差距的，白果就算不关机也一直流畅。可能白果有独显+分辨率低有一定优势，，不过黑果刚开机跟那个流畅度也差不多。
> 下个电脑就蹲几年后的arm mbp了，现在日常开发都是y9000x黑果也挺爽的，嘿嘿

uhd630肯定没有白果的独显好，白果的流畅最主要得益于独显的图像性能，用久了会卡这种事，感觉很玄学

**Comment by wuweijavadeveloper** [comment]
> > 大家有这个体验吗？开机的时候特别流畅，用几天之后 软件比如浏览器滑动会经常掉帧，虽然不至于卡顿，但对比了一下白果，发现还是有差距的，白果就算不关机也一直流畅。可能白果有独显+分辨率低有一定优势，，不过黑果刚开机跟那个流畅度也差不多。
> > 下个电脑就蹲几年后的arm mbp了，现在日常开发都是y9000x黑果也挺爽的，嘿嘿
> 
> uhd630肯定没有白果的独显好，白果的流畅最主要得益于独显的图像性能，用久了会卡这种事，感觉很玄学

请问下CFG lock解锁之后流畅度会有提升吗？对比了双系统的win10，就chorme而言，流畅度真的有点被win10暴打，我降分辨率到1080p才能跟win10差不多流畅，感觉uhd630再水，也不至于4k滑动网页都掉帧吧
