### ISSUE TITLE
能否给4K屏幕加一个2K的分辨率选项？

### ISSUE THREAD

**Issue by kidd808** [WangRicky/Y9000X-HACKINTOSH#37]
![WechatIMG7](https://user-images.githubusercontent.com/30661878/91961178-6b777400-ed3d-11ea-9ee5-fc6738629f2d.jpeg)

hi，

我不知道是我用的不对，还是本来就没有。目前4K屏幕只能选择到1920*1080。我是用了SwitchResX自己编辑的，可以实现2K缩放，但是感觉用户体验比较不好。望回复。

同时，多谢提供EFI。

**Comment by WangRicky** [comment]
这是正常的，macOS自动给4K屏幕开了hidpi，hidpi下4k最大ui可选分辨率就只有1080了

**Comment by kidd808** [comment]
收到，多谢
