### ISSUE TITLE
最新的更新蓝牙无法驱动

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#38]
更换了新的efi更新，开机蓝牙无法驱动，断电5分钟大法也没好用，更新了黑果小兵的2.5.5蓝牙驱动一样没有驱动，也许是我的操作不对？

**Comment by hx2nn** [comment]
换回之前的efi重启蓝牙就可以驱动了，应该还是哪里的改变我的机器没有适配。。。。

**Comment by WangRicky** [comment]
> 换回之前的efi重启蓝牙就可以驱动了，应该还是哪里的改变我的机器没有适配。。。。

请同时更新usb定制驱动
