### ISSUE TITLE
改为16,4后蓝牙不可用了

### ISSUE THREAD

**Issue by ImKujio** [WangRicky/Y9000X-HACKINTOSH#39]
如题，仅仅改了版本。
蓝牙以及相关的驱动都已经更新到8月3号的版本
OC版本为0.6正式版
![image](https://user-images.githubusercontent.com/18486297/92442362-52aa0b00-f1e2-11ea-93e2-4dfa492206da.png)
![image](https://user-images.githubusercontent.com/18486297/92442402-67869e80-f1e2-11ea-9afd-6e4a588dfb84.png)

**Comment by ImKujio** [comment]
问题找到了，是我的USB定制的有问题，导致网卡在PCI里，重新找了别人的USBPort换上之后就好了

**Comment by ziyue-pan** [comment]
> 问题找到了，是我的USB定制的有问题，导致网卡在PCI里，重新找了别人的USBPort换上之后就好了

可以问问是用的哪一份USBPort吗？

**Comment by ImKujio** [comment]
你需要的话，回我我发你一份

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Ziyue Pan <notifications@github.com&gt;
发送时间: 2020年10月7日 13:24
收件人: WangRicky/Y9000X-HACKINTOSH <Y9000X-HACKINTOSH@noreply.github.com&gt;
抄送: Kujio <291460573@qq.com&gt;, State change <state_change@noreply.github.com&gt;
主题: 回复：[WangRicky/Y9000X-HACKINTOSH] 改为16,4后蓝牙不可用了 (#39)





  
问题找到了，是我的USB定制的有问题，导致网卡在PCI里，重新找了别人的USBPort换上之后就好了
  
可以问问是用的哪一份USBPort吗？

**Comment by ziyue-pan** [comment]
谢谢，我已经解决了🙏，吃上完美黑苹果了

**Comment by deamonssouls** [comment]
能麻烦发我一份吗
