### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by guchengod** [WangRicky/Y9000X-HACKINTOSH#4]
睡眠唤醒有问题 睡眠定制USB解决之后解决 但是唤醒黑屏 老哥有什么好的方法了吗

**Comment by guchengod** [comment]
唤醒之后屏幕亮了 但是还是没有完全显示 应该是电源驱动的问题

**Comment by WangRicky** [comment]
> 唤醒之后屏幕亮了 但是还是没有完全显示 应该是电源驱动的问题

比如键盘唤醒，按一下之后键盘灯亮了，再按一下才显示吗？

**Comment by guchengod** [comment]
> > 唤醒之后屏幕亮了 但是还是没有完全显示 应该是电源驱动的问题
> 
> 比如键盘唤醒，按一下之后键盘灯亮了，再按一下才显示吗？

不是 按了一下键盘灯亮了屏幕也亮了 就是亮的屏幕是黑色的 没有完全点亮 但是能明显感觉到不是黑屏的状态了 电源键也亮了 风扇也开始转了

**Comment by bluezsd** [comment]
> > > 唤醒之后屏幕亮了 但是还是没有完全显示 应该是电源驱动的问题
> > 
> > 
> > 比如键盘唤醒，按一下之后键盘灯亮了，再按一下才显示吗？
> 
> 不是 按了一下键盘灯亮了屏幕也亮了 就是亮的屏幕是黑色的 没有完全点亮 但是能明显感觉到不是黑屏的状态了 电源键也亮了 风扇也开始转了

你的机型的屏幕是不是FHD版本的？我FHD版本的用这个EFI也有睡眠唤醒黑屏的问题，用programbw大神的可以正常唤醒，虽然睡眠和唤醒的速度都有点慢，但起码可以用，你可以试试用他的EFI看看行不行。具体是什么原因也不太清楚。

**Comment by guchengod** [comment]
> > > > 唤醒之后屏幕亮了 但是还是没有完全显示 应该是电源驱动的问题
> > > 
> > > 
> > > 比如键盘唤醒，按一下之后键盘灯亮了，再按一下才显示吗？
> > 
> > 
> > 不是 按了一下键盘灯亮了屏幕也亮了 就是亮的屏幕是黑色的 没有完全点亮 但是能明显感觉到不是黑屏的状态了 电源键也亮了 风扇也开始转了
> 
> 你的机型的屏幕是不是FHD版本的？我FHD版本的用这个EFI也有睡眠唤醒黑屏的问题，用programbw大神的可以正常唤醒，虽然睡眠和唤醒的速度都有点慢，但起码可以用，你可以试试用他的EFI看看行不行。具体是什么原因也不太清楚。

programbw大神也弄了这个机型吗？ 在哪？

**Comment by bluezsd** [comment]
programbw大神的机型是FHD的，地址 https://github.com/programbw/y9000x

**Comment by guchengod** [comment]
> programbw大神的机型是FHD的，地址 https://github.com/programbw/y9000x

我试了一下 他的EFI 还是黑屏 看来得好好研究一下日志了

**Comment by bluezsd** [comment]
> > programbw大神的机型是FHD的，地址 https://github.com/programbw/y9000x
> 
> 我试了一下 他的EFI 还是黑屏 看来得好好研究一下日志了

他的EFI睡眠和唤醒都要等一下的，睡眠需要等到电源灯一闪一闪的时候，按电源键后就不会闪了，然后等个10-20秒的样子，就会亮屏了，不是马上亮屏的，你可以再试试，如果还是不行就得另外想办法了。

**Comment by guchengod** [comment]
> > > programbw大神的机型是FHD的，地址 https://github.com/programbw/y9000x
> > 
> > 
> > 我试了一下 他的EFI 还是黑屏 看来得好好研究一下日志了
> 
> 他的EFI睡眠和唤醒都要等一下的，睡眠需要等到电源灯一闪一闪的时候，按电源键后就不会闪了，然后等个10-20秒的样子，就会亮屏了，不是马上亮屏的，你可以再试试，如果还是不行就得另外想办法了。

你那个就是睡死关机了 然后唤醒启动的 我已经解决了 把网卡内存主板内建已经可以完美睡眠唤醒了

**Comment by bluezsd** [comment]
> programbw大神的机型是FHD的，地址 https://github.com/programbw/y9000x
> 
> 我试了一下 他的EFI 还是黑屏 看来得好好研究一下日志了
> 
> 他的EFI睡眠和唤醒都要等一下的，睡眠需要等到电源灯一闪一闪的时候，按电源键后就不会闪了，然后等个10-20秒的样子，就会亮屏了，不是马上亮屏的，你可以再试试，如果还是不行就得另外想办法了。
> 
> 你那个就是睡死关机了 然后唤醒启动的 我已经解决了 把网卡内存主板内建已经可以完美睡眠唤醒了

请问怎么内建网卡内存主板？

**Comment by guchengod** [comment]
![image](https://user-images.githubusercontent.com/21252591/70334071-acf6f380-187f-11ea-9972-0222d41f457f.png)
其他类似

**Comment by guchengod** [comment]
![image](https://user-images.githubusercontent.com/21252591/70334162-dc0d6500-187f-11ea-96ec-c31db04391ed.png)
其他类似

**Comment by meetljm** [comment]
> ![image](https://user-images.githubusercontent.com/21252591/70334162-dc0d6500-187f-11ea-96ec-c31db04391ed.png)
> 其他类似

请问这个在哪里设置的

**Comment by guchengod** [comment]
> > ![image](https://user-images.githubusercontent.com/21252591/70334162-dc0d6500-187f-11ea-96ec-c31db04391ed.png)
> > 其他类似
> 
> 请问这个在哪里设置的

clver的propritis里
