### ISSUE TITLE
开机进入后屏幕亮度非常低

### ISSUE THREAD

**Issue by Sulisong** [WangRicky/Y9000X-HACKINTOSH#42]
电脑配置：屏幕 4k；处理器 i7 9750h；

你好作者，一直有关注你的开源，有几次尝试您的EFI,一直都存在一个问题，至今没有解决，所以来请教一下。就是开机进入后屏幕亮度非常低，屏幕非常暗，然后大概十几分钟后才显示正常亮度。

**Comment by moqi2011** [comment]
填写三码后就正常了

**Comment by Sulisong** [comment]
原来是这样子，我有时间试试





------------------ 原始邮件 ------------------
发件人: 吴奈 <notifications@github.com&gt;
发送时间: 2020年9月15日 01:34
收件人: WangRicky/Y9000X-HACKINTOSH <Y9000X-HACKINTOSH@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[WangRicky/Y9000X-HACKINTOSH] 开机进入后屏幕亮度非常低 (#42)





 
填写三码后就正常了

**Comment by Sulisong** [comment]
感谢，测试了注入三码可以正常使用了。很意外，可以直接更新macOS Big Sur
![image](https://user-images.githubusercontent.com/40148554/93280797-13407780-f7fd-11ea-857c-d4a1563518ba.png)

**Comment by WangRicky** [comment]
> 感谢，测试了注入三码可以正常使用了。很意外，可以直接更新macOS Big Sur
> ![image](https://user-images.githubusercontent.com/40148554/93280797-13407780-f7fd-11ea-857c-d4a1563518ba.png)

理论上oc0.6.0已经支持big sur了，个人由于作为主力办公机，测试版本的系统还是不太愿意更新

**Comment by Sulisong** [comment]
4k显示器要注入EDID，不然安装完成会黑屏。个人测试了一下，macOS Big Sur beta6非常稳定，可以尝试，嘿嘿😁


发自我的iPhone

------------------ 原始邮件 ------------------
发件人: WangRicky <notifications@github.com&gt;
发送时间: 2020年9月16日 15:42
收件人: WangRicky/Y9000X-HACKINTOSH <Y9000X-HACKINTOSH@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[WangRicky/Y9000X-HACKINTOSH] 开机进入后屏幕亮度非常低 (#42)





  
感谢，测试了注入三码可以正常使用了。很意外，可以直接更新macOS Big Sur
 
  
理论上oc0.6.0已经支持big sur了，个人由于作为主力办公机，测试版本的系统还是不太愿意更新

**Comment by moqi2011** [comment]
我没有注入EDID也是正常的呢。

**Comment by Sulisong** [comment]
> 我没有注入EDID也是正常的呢。

也是macOS Big Sur吗？

**Comment by moqi2011** [comment]
> > 我没有注入EDID也是正常的呢。
> 
> 也是macOS Big Sur吗？

不是哦，是10.15.6

**Comment by Sulisong** [comment]
好的，我说的的Big sur的情况哦，嘿嘿





------------------ 原始邮件 ------------------
发件人: 吴奈 <notifications@github.com&gt;
发送时间: 2020年9月20日 12:05
收件人: WangRicky/Y9000X-HACKINTOSH <Y9000X-HACKINTOSH@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[WangRicky/Y9000X-HACKINTOSH] 开机进入后屏幕亮度非常低 (#42)





   
我没有注入EDID也是正常的呢。
  
也是macOS Big Sur吗？
  
不是哦，是10.15.6

**Comment by zorroye** [comment]
问下1080P怎么去掉4k补丁？ 谢谢 
这个设置为01，
OpenCore Configurator -> NVRAM -> 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 -> UIScale: 01
这个要怎么设置吗？
OpenCore Configurator -> DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0)

**Comment by yaotutu** [comment]
> 问下1080P怎么去掉4k补丁？ 谢谢
> 这个设置为01，
> OpenCore Configurator -> NVRAM -> 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 -> UIScale: 01
> 这个要怎么设置吗？
> OpenCore Configurator -> DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0)


Device删除整个 PciRoot(0x0)/Pci(0x2,0x0) 试试。 我的电脑进售后了，没在手边，没法测试。具体的在issue已关闭的问题中有一个反应黑屏问题的，就是这样解决的。

**Comment by cuteluo1983** [comment]
> 感谢，测试了注入三码可以正常使用了。很意外，可以直接更新macOS Big Sur
> ![image](https://user-images.githubusercontent.com/40148554/93280797-13407780-f7fd-11ea-857c-d4a1563518ba.png)

兄弟，你直升big sur成功了？我无论是系统直升还是做启动盘升级，都卡进度条...

**Comment by Sulisong** [comment]
直接升的，重启了n次，推荐把日志打开，可能有部分驱动会导致卡进度，升级时间比较久，耐心等待





------------------ 原始邮件 ------------------
发件人: cuteluo1983 <notifications@github.com&gt;
发送时间: 2020年10月19日 15:28
收件人: WangRicky/Y9000X-HACKINTOSH <Y9000X-HACKINTOSH@noreply.github.com&gt;
抄送: 苏lisong <1183148426@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[WangRicky/Y9000X-HACKINTOSH] 开机进入后屏幕亮度非常低 (#42)





  
感谢，测试了注入三码可以正常使用了。很意外，可以直接更新macOS Big Sur
 
  
兄弟，你直升big sur成功了？我无论是系统直升还是做启动盘升级，都卡进度条...

**Comment by EugeneSnikhovskiy** [comment]
For anyone who already fill tree codes and screen brightness still low - [this patches](https://www.tonymacx86.com/threads/maximum-brightness-gets-reduced-by-using-wegnoegpu.288969/#post-2048162) helped for me
