### ISSUE TITLE
OpenCore 0.6.2出啦

### ISSUE THREAD

**Issue by ukhack** [WangRicky/Y9000X-HACKINTOSH#43]
修正了一些问题？
https://github.com/williambj1/OpenCore-Factory/releases

**Comment by WangRicky** [comment]
> 修正了一些问题？
> https://github.com/williambj1/OpenCore-Factory/releases

目前只更新正式本，以稳定为主，0.6.1主要支持了big sur和旧版本的mac系统，所以暂时也没有升级
