### ISSUE TITLE
原生Wifi6网卡ax200已经支持 原生Wi-Fi、定位、接力、智能热点啦！

### ISSUE THREAD

**Issue by ukhack** [WangRicky/Y9000X-HACKINTOSH#45]
从小新pro13那边看到的。效果应该比dw1820a好一些。
我没有折腾成功，可能是什么地方配置的不对。有兴趣去看一下吧
https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases

**Comment by ukhack** [comment]
如果大神成功了，记得分享一下心得啊

**Comment by WangRicky** [comment]
> 从小新pro13那边看到的。效果应该比dw1820a好一些。
> 我没有折腾成功，可能是什么地方配置的不对。有兴趣去看一下吧
> https://github.com/daliansky/XiaoXinPro-13-hackintosh/releases

已经测试过了，效果比dw1820a还是有差距的，5g只能工作在20Mhz，并且不支持隔空投送，暂时不考虑更换回来

**Comment by hefushe** [comment]
成功用ax200驱动基本完美功能！定位、隔空投屏都没有问题
[https://github.com/OpenIntelWireless/itlwm/releases](url)

**Comment by laoxiajiadeyun** [comment]
> 成功用ax200驱动基本完美功能！定位、隔空投屏都没有问题
> [https://github.com/OpenIntelWireless/itlwm/releases](url)

所以可以只更换硬盘了是吗？

**Comment by hekaimsbl** [comment]
> > 成功用ax200驱动基本完美功能！定位、隔空投屏都没有问题
> > [https://github.com/OpenIntelWireless/itlwm/releases](url)
> 
> 所以可以只更换硬盘了是吗？
硬盘也可以打屏蔽补丁，这个仓库就有，屏蔽的是第一个硬盘位
