### ISSUE TITLE
只显示硬盘温度

### ISSUE THREAD

**Issue by zorroye** [WangRicky/Y9000X-HACKINTOSH#46]
我把相关的kext都放上去了，但是istat menus只显示硬盘温度，其他都没显示。。

**Comment by XuToTo** [comment]
似乎是因为 kext 没有 SMCProcessor 的原因

**Comment by hx2nn** [comment]
我的也是只显示硬盘温度，希望有解决方法

**Comment by WangRicky** [comment]
> 我的也是只显示硬盘温度，希望有解决方法

SMCProcessor这个驱动放一下试试，我是不太在意这些信息，所以没研究，如果需要的人多，可以研究一下

**Comment by zorroye** [comment]
> > 我的也是只显示硬盘温度，希望有解决方法
> 
> SMCProcessor这个驱动放一下试试，我是不太在意这些信息，所以没研究，如果需要的人多，可以研究一下

**Comment by zorroye** [comment]
> > 我的也是只显示硬盘温度，希望有解决方法
> 
> SMCProcessor这个驱动放一下试试，我是不太在意这些信息，所以没研究，如果需要的人多，可以研究一下

谢谢大神回复，是这样的，
这几个kext都加进去了，
配置文件里面kernel也加入了，
用cleanmymac 能显示cpu温度。
用istat menus 只显示硬盘温度。

**Comment by wangwbwwb** [comment]
> > > 我的也是只显示硬盘温度，希望有解决方法
> > 
> > 
> > SMCProcessor这个驱动放一下试试，我是不太在意这些信息，所以没研究，如果需要的人多，可以研究一下
> 
> 谢谢大神回复，是这样的，
> 这几个kext都加进去了，
> 配置文件里面kernel也加入了，
> 用cleanmymac 能显示cpu温度。
> 用istat menus 只显示硬盘温度。

修改机型为16,1
