### ISSUE TITLE
严格来说不能算是Issues，看看这样的蓝牙方案是否可行？？？

### ISSUE THREAD

**Issue by gwjtssy** [WangRicky/Y9000X-HACKINTOSH#47]
1、购买一个简易的蓝牙音箱，一定要立体声的，拆了，电路板取出。
2、将电路板内置在y9000x内，供电要好好找找，大概率5v应该可以，将输出和两个内置扬声器并联在一起。这样，windows的时候用内置，其它系统的时候用蓝牙。
3、就是不知道和内置扬声器并联后，因为负载阻值变化，长时间使用会不会出问题？

**Comment by Corazon0513** [comment]
如果非得用内置扬声器的话 比较简易的方案是
将ALC285的双声道模拟输出引出 -> 接入替代的功放模块 -> 并入扬声器输入

**Comment by current-liu** [comment]
@gwjtssy 我也是y9000x FHD 1080,也遇到了睡眠唤醒后只有背光不亮屏的问题,你提到的```整个设备PciRoot(0x0)/Pci(0x2,0x0)```能否说的详细一点,不胜感激.

**Comment by gwjtssy** [comment]
我买了一块5v功放板和一个5v蓝牙功放板，都很小。苦于无法从主板上取5v电，而且功率要达到功放板要求所以无法下手。蓝牙功放板，应该是最简易的方案？为什么这么说呢？因为只要取得5v供电，将原机喇叭接到蓝牙功放板上就行，破线最少，也最安全，但是蓝牙的其它设备（比如蓝牙鼠标）将无法再使用。
你说的方案，我想过，替代的功放模块不好找，引脚一样、功能一样的几乎没有。
如果不使用蓝牙功放板的方案，可以采用功放板方案，因为耳机能发生，从耳机小板引线到功放板，原机喇叭接功放板即可。但也会涉及到5v取电的问题。我暂时不敢下手。

**Comment by hx2nn** [comment]
期待大神的解决，感谢
