### ISSUE TITLE
添加三码以后，系统设置里找不到蓝牙了

### ISSUE THREAD

**Issue by deamonssouls** [WangRicky/Y9000X-HACKINTOSH#48]
最近添加三码以后蓝牙的设置就不见了，应该怎么手动添加上去？

**Comment by hefushe** [comment]
我也遇到同样问题了，不知道怎么解决，发现只要不改System Product Name 里的MacBookPro14,1蓝牙就不会有问题，不知道是不是这个原因

**Comment by deamonssouls** [comment]
我已经修改成16，4，且登录apple id了，还可以换三码吗？

**Comment by hx2nn** [comment]
这个efi还是比较稳定的，既然已经改了16.4就不要再往回调整了。之前遇到过蓝牙问题 ，但是新的efi没有这种问题，只需要更新下三码，注意occ版本要支持oc0.6.2，基本上不会有问题。（先推出id登陆，重启以后重新更新三码后再次登陆id）

**Comment by HiramChen-CN** [comment]
你用16,1的机型和三码试试？我用的16,1，我觉得比较完美了，很多kext也支持到了16,1，不知道16,4的支持情况怎样，但是机型比较新，有些kext可能需要自己改才能支持，比如usb的kext
