### ISSUE TITLE
CFG Lock解锁遇到问题

### ISSUE THREAD

**Issue by hekaimsbl** [WangRicky/Y9000X-HACKINTOSH#50]
提取到的ffs文件有900多k

用'Universal IFR Extractor.exe'解释时，能正确识别为UEFI 但是在目录中没有看到Txt文件

请问楼主用的也是这个工具 吗

我将ffs文件和工具压缩了一下

[ffs file.zip](https://github.com/WangRicky/Y9000X-HACKINTOSH/files/5384088/ffs.file.zip)

**Comment by cuteluo1983** [comment]
大多数人都不建议解锁CFG

**Comment by hekaimsbl** [comment]
已经解锁了

原因是用UEFITool提取的时候应该选择`Extract body...`

<img width="766" alt="提取EFI" src="https://user-images.githubusercontent.com/43072224/96218908-4cb10200-0fb8-11eb-9828-868c22ff2664.png">
