### ISSUE TITLE
提醒：OC引导进入Windows系统，蓝屏

### ISSUE THREAD

**Issue by cuteluo1983** [WangRicky/Y9000X-HACKINTOSH#52]
作为一个不懂技术的新人，提醒下各位新手用户，因为OC的问题，用Ricky的EFI引导进入Windows系统，win10会蓝屏，提示ACPI_Error，所以推荐用F12的方式选择启动盘，进入win10....
我一直以为是精简版win10的问题，又换回msdn原版，还是蓝屏，最后问了群友得知真正的原因，失眠了...

**Comment by HiramChen-CN** [comment]
并不算OC的问题，是dsdt热补丁需要做系统判断兼容，一般的dsdt补丁都懒得做兼容，因为黑了苹果之后win就很少开了，需要的可以自己做兼容，补丁也不算多，应该还是好弄的，就是需要注意重命名的补丁，重命名的补丁没办法加系统判断，需要在dsdt补丁里做多系统兼容

**Comment by cuteluo1983** [comment]
> 并不算OC的问题，是dsdt热补丁需要做系统判断兼容，一般的dsdt补丁都懒得做兼容，因为黑了苹果之后win就很少开了，需要的可以自己做兼容，补丁也不算多，应该还是好弄的，就是需要注意重命名的补丁，重命名的补丁没办法加系统判断，需要在dsdt补丁里做多系统兼容

谢谢大神回复，小白不懂这么多，就是提醒下其他小白，要用F12切换系统。
另外，Y9000X多黑果用户，双系统多居多吧，不过为了一个更好体验，做这么多测试工作，确实是个累活
