### ISSUE TITLE
10875h版本  可以写入正常写入三码，但亮度没有变化，还是非常低

### ISSUE THREAD

**Issue by carsonlius** [WangRicky/Y9000X-HACKINTOSH#53]
No suitable signature - Security Violation

**Comment by carsonlius** [comment]
最新版本 2020.10.23

**Comment by carsonlius** [comment]
更新到15.7版本 可以写入正常写入三码，但亮度没有变化，还是非常低

**Comment by cuteluo1983** [comment]
> 更新到15.7版本 可以写入正常写入三码，但亮度没有变化，还是非常低

你要描述你的操作步骤，好帮你判断。
我是全新安装的15.7，预先已经弄好了三码，然后执行安装后，再把EFI文件夹复制进去分区，没有出现亮度的问题

**Comment by carsonlius** [comment]
我的机器是 10875 2020版本

1. 使用EFI进入系统，此时亮度低
2. GenSMBIOS生成三码,ProperTree写入三码
3.  重启发现三码已经成功注入， 此时亮度还是低

**Comment by EugeneSnikhovskiy** [comment]
I use open core config from this repo and my screen is fullHD. For me helped to replace **SSDT-PNLF.aml** from this repo to files from [Brightness_CFL.zip](https://www.tonymacx86.com/threads/maximum-brightness-gets-reduced-by-using-wegnoegpu.288969/#post-2048162). Also note that brightness value is low by default and need to be increased in settings

**Comment by carsonlius** [comment]
@EugeneSnikhovskiy 
What is the configuration of your y9000x?

**Comment by EugeneSnikhovskiy** [comment]
@carsonlius I have model with i7-10750h + fullHD screen. But as I know **SSDT-PNLF.aml** is for older processors than 9 gen. For cofee lake and more new gen we need to use **SSDT-PNLFCFL.aml**. Where **CFL** name postfix is Cofee lake

**Comment by carsonlius** [comment]
@EugeneSnikhovskiy 

how to set ?
``` 
I use open core config from this repo and my screen is fullHD. For me helped to replace SSDT-PNLF.aml from this repo to files from Brightness_CFL.zip. Also note that brightness value is low by default and need to be increased in settings
```

>

**Comment by EugeneSnikhovskiy** [comment]
@carsonlius 
1. You need to add **SSDT-PNLFCFL.aml** file to **efi/oc/acpi** folder
2. Then open **config.plist** file from **efi/oc** folder with open core configurator
3. Navigate to **ACPI** tab
4. Find line with **SSDT-PNLF.aml** and remove **enabled** checkbox
5. Add new line with **SSDT-PNLFCFL.aml** (click on plus icon and fill **path** as **SSDT-PNLFCFL.aml** and **comment** as **SSDT-PNLFCFL** and turn on enabled checkbox)
6. Save config (file => save)

**Comment by carsonlius** [comment]
@EugeneSnikhovskiy 
It works! 
thanks a  lot

**Comment by EugeneSnikhovskiy** [comment]
@carsonlius great to hear it :)
But there are one more bug.

For now if you want to use second display with "usb-c to hdmi" adapter it will work. But when you turn on notebook with plugged in hdmi - you will see black internal screen and worked external. If you go to sleep mode and than wake up - all screens will works. Or you can eject hdmi before turn on notebook and plug in after system load. And all displays will work correctly.

With old **SSDT-PNLF.aml** this bug is not exist, but brightness is broken. Unfortunately I don't know how to fix it. If you also need second monitor and you find solution, please let me know.

**Comment by carsonlius** [comment]
@EugeneSnikhovskiy 

if i find a solution，i will tell you

**Comment by carsonlius** [comment]
> @carsonlius great to hear it :)
> But there are one more bug.
> 
> For now if you want to use second display with "usb-c to hdmi" adapter it will work. But when you turn on notebook with plugged in hdmi - you will see black internal screen and worked external. If you go to sleep mode and than wake up - all screens will works. Or you can eject hdmi before turn on notebook and plug in after system load. And all displays will work correctly.
> 
> With old **SSDT-PNLF.aml** this bug is not exist, but brightness is broken. Unfortunately I don't know how to fix it. If you also need second monitor and you find solution, please let me know.

@EugeneSnikhovskiy It has fixed
