### ISSUE TITLE
dw1280a在win10下驱动失败

### ISSUE THREAD

**Issue by current-liu** [WangRicky/Y9000X-HACKINTOSH#54]
- 在macOS下正常
- win10下用的黑果小兵帖子里的驱动，蓝牙正常
- wifi的驱动在设备管理里面更新驱动时耗时异常地长且最后会失败，有遇到相同问题的朋友吗
- 配置：16G+1T+FHD+i7

**Comment by Soldat-D** [comment]
自动更新？去戴尔官网下载啊

**Comment by cuteluo1983** [comment]
> * 在macOS下正常
> * win10下用的黑果小兵帖子里的驱动，蓝牙正常
> * wifi的驱动在设备管理里面更新驱动时耗时异常地长且最后会失败，有遇到相同问题的朋友吗
> * 配置：16G+1T+FHD+i7

DW1820A微软的驱动不行，要单独安装，自己去下载安装
[DW1820A_for_Windows_Drivers.zip](https://github.com/WangRicky/Y9000X-HACKINTOSH/files/5485578/DW1820A_for_Windows_Drivers.zip)

**Comment by current-liu** [comment]
上面的驱动以及dell官网的最新驱动都试过，都失败了；
一个现象是安装wifi驱动时间也明显长的多，是蓝牙驱动的好几倍

**Comment by Soldat-D** [comment]
说明你找的不对啊  https://www.dell.com/support/home/zh-cn/drivers/driversdetails?driverId=58FTM

**Comment by current-liu** [comment]
多谢老哥，虽然还是失败了
又用驱动精灵试了下，也没成功，放弃了
