### ISSUE TITLE
准备折腾升级big sur。。。。。

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#55]
不是主力机，给大家做个先驱实验吧，回头报告

**Comment by moqi2011** [comment]
直接升级然后卡住了...

**Comment by hx2nn** [comment]
一样，重启选择install后直接黑屏，时间机器恢复中

**Comment by hx2nn** [comment]
![Uploading 28669BBE-4ABE-4AA9-AA32-A5D27B79091E.jpeg…]()
大神帮忙看看

**Comment by WangRicky** [comment]
4k内屏无法点亮为已知问题，可以注入edid，修改刷新率为48hz解决，无需恢复旧版，可参考http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1866466&extra=&page=4&mobile=yes

**Comment by hx2nn** [comment]
![1F86EBD4-6850-4A78-8C63-7CB108C49D9C](https://user-images.githubusercontent.com/57549367/99137624-12925900-2667-11eb-9722-8e561abfc278.jpeg)

**Comment by hx2nn** [comment]
这个难度有点大

**Comment by hx2nn** [comment]
我家里的nuc8接的就是4k屏，昨天升级没问题啊。

**Comment by WangRicky** [comment]
> 我家里的nuc8接的就是4k屏，昨天升级没问题啊。

只有笔记本内屏有问题，外接没问题

**Comment by hx2nn** [comment]
你啥时候升级啊？是不是更新efi就可以？我恢复时间机器呢

**Comment by hx2nn** [comment]
弄了一大顿，连提取edid都没弄明白怎么操作，等待大神升级后的教程啊，不说别的，谢谢了

**Comment by moqi2011** [comment]
重新安装还是不能正常安装,只有先继续使用Catalina了.
你们使用的时候会不会出现盒盖后WIFI就断开?
