### ISSUE TITLE
Type-C接显示器，不能选择用显示器的音响

### ISSUE THREAD

**Issue by laoxiajiadeyun** [WangRicky/Y9000X-HACKINTOSH#56]
大佬好，请问一下你有试过typeC直连显示器吗？ 我直连显示正常，但是显示器上的音响设备无法选择，自带的扬声器也不能驱动，有点无奈····· 如下只能选择内置扬声器
<img width="668" alt="Snipaste_2020-11-22_16-25-48" src="https://user-images.githubusercontent.com/30768343/99898978-cbe4d480-2ce0-11eb-8788-ca3dab12563f.png">

是声卡的问题吗？我该从那儿优化呢

**Comment by WangRicky** [comment]
> 大佬好，请问一下你有试过typeC直连显示器吗？ 我直连显示正常，但是显示器上的音响设备无法选择，自带的扬声器也不能驱动，有点无奈····· 如下只能选择内置扬声器
> <img alt="Snipaste_2020-11-22_16-25-48" width="668" src="https://user-images.githubusercontent.com/30768343/99898978-cbe4d480-2ce0-11eb-8788-ca3dab12563f.png">
> 
> 是声卡的问题吗？我该从那儿优化呢

应该不是声卡的问题，是DP接口的问题，可以尝试修改显卡的注入参数，我手头的显示器，没有扬声器，所以暂时没法调试

**Comment by laoxiajiadeyun** [comment]
> > 大佬好，请问一下你有试过typeC直连显示器吗？ 我直连显示正常，但是显示器上的音响设备无法选择，自带的扬声器也不能驱动，有点无奈····· 如下只能选择内置扬声器
> > <img alt="Snipaste_2020-11-22_16-25-48" width="668" src="https://user-images.githubusercontent.com/30768343/99898978-cbe4d480-2ce0-11eb-8788-ca3dab12563f.png">
> > 是声卡的问题吗？我该从那儿优化呢
> 
> 应该不是声卡的问题，是DP接口的问题，可以尝试修改显卡的注入参数，我手头的显示器，没有扬声器，所以暂时没法调试

好 我再看看

**Comment by laoxiajiadeyun** [comment]
解决啦～

**Comment by laoxiajiadeyun** [comment]
解决啦～
参考这个链接：http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1875837&highlight=dp%2B%C9%F9%D2%F4
在oc中加入下面两条配置就OK了：
![image](https://user-images.githubusercontent.com/30768343/99899826-1bc69a00-2ce7-11eb-81b1-cf60030b3600.png)
