### ISSUE TITLE
触控板间歇性的卡顿，时长约1秒,然后恢复正常

### ISSUE THREAD

**Issue by carsonlius** [WangRicky/Y9000X-HACKINTOSH#58]
系统： 10.15.7
配置:   10875h  1080p

**Comment by carsonlius** [comment]
复现方式：触控板做为操控的笔记本的唯一方式使用, 这是必现的问题

**Comment by carsonlius** [comment]
更新了现在这一版本的efi， 暂时已经没有问题了

**Comment by zhbhun** [comment]
你好，我也遇到了触摸板间歇性卡顿的情况，系统也是 10.15.7，用的是最新的 EFI https://github.com/WangRicky/Y9000X-HACKINTOSH/tree/88b31df0c122425b75bd369ce756274fb9851c74 。请问你用的是哪个版本的 EFI？还有想请教下，你的触摸板三指拖动是否能够中断后继续拖拽。
