### ISSUE TITLE
反馈一个解锁会卡死机的bug

### ISSUE THREAD

**Issue by laoxiajiadeyun** [WangRicky/Y9000X-HACKINTOSH#60]
最近使用一直有一个bug，就是睡眠后解锁，解锁完过个两三秒左右 电脑会卡死，什么也做不了，只能强行关机，不知道有没有人有同样的问题，排查了好几个软件没发现原因，不知道是不是自己那块没搞好，重新换了这一版oc配置也会这样，有点苦恼。

这里附上几个系统崩溃日志吧，希望有会的大佬能帮忙看一下

[未命名 2.txt](https://github.com/WangRicky/Y9000X-HACKINTOSH/files/5714622/2.txt)
[未命名.txt](https://github.com/WangRicky/Y9000X-HACKINTOSH/files/5714623/default.txt)

**Comment by laoxiajiadeyun** [comment]
刚刚看了Corazon0513的配置，去Kernel里面把PowerTimeoutKernelPanic这个选项勾上以后，今晚暂时没出现过这个问题了，是否长期生效我用一段时间再进行反馈吧，大家如果有类似问题的可以试试：
https://github.com/Corazon0513/Y9000X-2020-i9-Hackintosh
![image](https://user-images.githubusercontent.com/30768343/102630902-19414e00-4188-11eb-978c-ede42bfa8625.png)
位置：
![image](https://user-images.githubusercontent.com/30768343/102631158-5f96ad00-4188-11eb-9944-59e84ea6bf49.png)

**Comment by laoxiajiadeyun** [comment]
然后我没有解锁CFG，想问一下解锁以后体验会优化很多吗？续航怎么样
我现在的续航也就2个小时左右吧。续航比Windows降了一半，非常耗电。
不知道其他人怎么样。

**Comment by carsonlius** [comment]
同续航之后2个小时左右

**Comment by kidd808** [comment]
@laoxiajiadeyun  休眠结束之后的问题，我这边有两种：

1. 笔记本没有盖上的休眠，我需要按电源键唤醒，之后，有概率会键盘错乱。所以，我如果忘记盖盖子而休眠，我经常会使用盖盖子在打开来进行唤醒（不知道算不算是迷信）。

2. 第二种和你一样，就是会不亮，这种概率还低于我说的上面这种，很低。

**Comment by kidd808** [comment]
@laoxiajiadeyun  我前两天升了 big sur。 各种折腾在，最后应该是复现了你说的问题。根据你的提示，改了，就好了

**Comment by laoxiajiadeyun** [comment]
> @laoxiajiadeyun 我前两天升了 big sur。 各种折腾在，最后应该是复现了你说的问题。根据你的提示，改了，就好了

我这改了以后用了一个月了，目前都没发现这个问题了，所以这个方法应该是有效解决了

**Comment by bzh1024** [comment]
同样遇到这个问题，没有勾选 PowerTimeoutKernelPanic，睡眠后开机过几秒必死机，勾选后暂时没有遇到了。
