### ISSUE TITLE
Mac big sur 4k屏60hz刷新解决方法

### ISSUE THREAD

**Issue by Sulisong** [WangRicky/Y9000X-HACKINTOSH#61]
http://bbs.pcbeta.com/viewthread-1878795-1-2.html
大佬可以试试这个方法

**Comment by XuToTo** [comment]
歪一下，大佬们有没有试过直接从 Catalina 升到 Big Sur 的？需要注意些什么吗？

**Comment by Sulisong** [comment]
我之前是Catalina直接升的，开了哆嗦模式，看日志，把有错误的驱动暂时关掉。直接升可能需要重启多次且时间较长，耐心等待即可。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XuToTo"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 下午5:07
收件人: "WangRicky/Y9000X-HACKINTOSH"<Y9000X-HACKINTOSH@noreply.github.com&gt;; 
抄送: "苏lisong"<1183148426@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [WangRicky/Y9000X-HACKINTOSH] Mac big sur 4k屏60hz刷新解决方法 (#61)





 
歪一下，大佬们有没有试过直接从 Catalina 升到 Big Sur 的？需要注意些什么吗？

**Comment by XuToTo** [comment]
感谢！最近应该更新了驱动，可能过程会顺利些~

**Comment by Sulisong** [comment]
嗯嗯，祝顺顺利利




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XuToTo"<notifications@github.com&gt;; 
发送时间: 2020年12月24日(星期四) 晚上11:41
收件人: "WangRicky/Y9000X-HACKINTOSH"<Y9000X-HACKINTOSH@noreply.github.com&gt;; 
抄送: "苏lisong"<1183148426@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [WangRicky/Y9000X-HACKINTOSH] Mac big sur 4k屏60hz刷新解决方法 (#61)





 
感谢！最近应该更新了驱动，可能过程会顺利些~

**Comment by WangRicky** [comment]
> http://bbs.pcbeta.com/viewthread-1878795-1-2.html
> 大佬可以试试这个方法

新版已经支持了
