### ISSUE TITLE
1080p big sur 删除PciRoot(0x0)/Pci(0x2,0x0)开机黑屏

### ISSUE THREAD

**Issue by carsonlius** [WangRicky/Y9000X-HACKINTOSH#62]
配置: 1080p 10875h
环境：big sur 
操作：  
      注入三码,删掉PciRoot(0x0)/Pci(0x2,0x0)之后睡眠唤醒正常，但是开机黑屏
      如果保留PciRoot(0x0)/Pci(0x2,0x0)，无法唤醒但是开机正常

**Comment by HiramChen-CN** [comment]
直接删除这个节点其实是错误的黑果方式，无论是1080p的还是4k的，只要不是原生支持的屏（对黑果来说，一般的不可能），都应该注入egpu节点，以使显卡行为可控，而不是依赖weg的默认值。
对于Y9000X 1080P屏幕来说，正确的修改方式是保留这个节点，唯一与4k不同的应该仅仅需要修改如下两点：

### 4.5. 显示器1080P FHD版本适配

分辨率参考:

- 4K UHD（3840×2160）
- WQHD（2560×1440）
- Full HD（1920×1080）
- HD（1280×720）

**配置修改：**

- `OpenCore Configurator -> NVRAM -> 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 -> UIScale: 01`

  对于1080P显示器版本，需要将`UIScale`设置为`1`

  ```diff
  diff --git a/EFI/OC/config.plist b/EFI/OC/config.plist
  index 5b1bfc6..0bac981 100644
  --- a/EFI/OC/config.plist
  +++ b/EFI/OC/config.plist
  @@ -980,7 +1074,7 @@
                                  <key>DefaultBackgroundColor</key>
                                  <data>AAAAAA==</data>
                                  <key>UIScale</key>
  -                               <data>Ag==</data>
  +                               <data>AQ==</data>
                          </dict>
                          <key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
                          <dict>
  ```

- `OpenCore Configurator -> DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0) -> dpcd-max-link-rate: 0A000000`

  修改节点的属性值`dpcd-max-link-rate`为`0A000000`
  
  ```diff
  diff --git a/EFI/OC/config.plist b/EFI/OC/config.plist
  index 5b1bfc6..0bac981 100644
  --- a/EFI/OC/config.plist
  +++ b/EFI/OC/config.plist
  @@ -308,17 +510,27 @@
                                  <key>AAPL,ig-platform-id</key>
                                  <data>AACbPg==</data>
                                  <key>AAPL,slot-name</key>
                                  <string>Intel Internal Graphhics</string>
                                  <key>device-id</key>
                                  <data>mz4AAA==</data>
                                  <key>device_type</key>
                                  <string>VGA compatible controller</string>
                                  <key>dpcd-max-link-rate</key>
  -                               <data>FAAAAA==</data>
  +                               <data>CgAAAA==</data>
                                  <key>enable-dpcd-max-link-rate-fix</key>
                                  <data>AQAAAA==</data>
                                  <key>enable-hdmi20</key>
                                  <data>AQAAAA==</data>
                                  <key>framebuffer-patch-enable</key>
                                  <data>AQAAAA==</data>
                                  <key>framebuffer-unifiedmem</key>
  ```

**Comment by carsonlius** [comment]
@

> 直接删除这个节点其实是错误的黑果方式，无论是1080p的还是4k的，只要不是原生支持的屏（对黑果来说，一般的不可能），都应该注入egpu节点，以使显卡行为可控，而不是依赖weg的默认值。
> 对于Y9000X 1080P屏幕来说，正确的修改方式是保留这个节点，唯一与4k不同的应该仅仅需要修改如下两点：
> 
> ### 4.5. 显示器1080P FHD版本适配
> 分辨率参考:
> 
> * 4K UHD（3840×2160）
> * WQHD（2560×1440）
> * Full HD（1920×1080）
> * HD（1280×720）
> 
> **配置修改：**
> 
> * `OpenCore Configurator -> NVRAM -> 4D1EDE05-38C7-4A6A-9CC6-4BCCA8B38C14 -> UIScale: 01`
>   对于1080P显示器版本，需要将`UIScale`设置为`1`
>   ```diff
>   diff --git a/EFI/OC/config.plist b/EFI/OC/config.plist
>   index 5b1bfc6..0bac981 100644
>   --- a/EFI/OC/config.plist
>   +++ b/EFI/OC/config.plist
>   @@ -980,7 +1074,7 @@
>                                   <key>DefaultBackgroundColor</key>
>                                   <data>AAAAAA==</data>
>                                   <key>UIScale</key>
>   -                               <data>Ag==</data>
>   +                               <data>AQ==</data>
>                           </dict>
>                           <key>4D1FDA02-38C7-4A6A-9CC6-4BCCA8B30102</key>
>                           <dict>
>   ```
> * `OpenCore Configurator -> DeviceProperties -> PciRoot(0x0)/Pci(0x2,0x0) -> dpcd-max-link-rate: 0A000000`
>   修改节点的属性值`dpcd-max-link-rate`为`0A000000`
>   ```diff
>   diff --git a/EFI/OC/config.plist b/EFI/OC/config.plist
>   index 5b1bfc6..0bac981 100644
>   --- a/EFI/OC/config.plist
>   +++ b/EFI/OC/config.plist
>   @@ -308,17 +510,27 @@
>                                   <key>AAPL,ig-platform-id</key>
>                                   <data>AACbPg==</data>
>                                   <key>AAPL,slot-name</key>
>                                   <string>Intel Internal Graphhics</string>
>                                   <key>device-id</key>
>                                   <data>mz4AAA==</data>
>                                   <key>device_type</key>
>                                   <string>VGA compatible controller</string>
>                                   <key>dpcd-max-link-rate</key>
>   -                               <data>FAAAAA==</data>
>   +                               <data>CgAAAA==</data>
>                                   <key>enable-dpcd-max-link-rate-fix</key>
>                                   <data>AQAAAA==</data>
>                                   <key>enable-hdmi20</key>
>                                   <data>AQAAAA==</data>
>                                   <key>framebuffer-patch-enable</key>
>                                   <data>AQAAAA==</data>
>                                   <key>framebuffer-unifiedmem</key>
>   ```

正解，谢谢

**Comment by carsonlius** [comment]
@CyrilTaylor
