### ISSUE TITLE
0.66 0.65 0.64 efi耳机孔没有声音

### ISSUE THREAD

**Issue by carsonlius** [WangRicky/Y9000X-HACKINTOSH#64]
配置1080p  10代u
耳机孔插耳机没有声音

复现步骤：
      1. 注入三码
      2. 安装macos

**Comment by carsonlius** [comment]
big sur

**Comment by CzzzzzHyq** [comment]
我也是同样的问题，但降级bios到 v1.05 (CTEC20WW)后，恢复正常。
