### ISSUE TITLE
1080P无法安装，卡在第二次读条的开始

### ISSUE THREAD

**Issue by roobtyan** [WangRicky/Y9000X-HACKINTOSH#66]
不知道是什么情况，尝试了多次，也换了镜像，但是每次安装第一次读条很顺利，到了第二次的时候就会卡住，大佬能不能帮帮忙？

**Comment by liweidong1216** [comment]
顶配，4K同样也无法安装，也是卡在第二次启动的时候苹果LOGO处，CPU风扇狂转，只能强行关机~

**Comment by roobtyan** [comment]
> 顶配，4K同样也无法安装，也是卡在第二次启动的时候苹果LOGO处，CPU风扇狂转，只能强行关机~

可能是大佬忘记改某些地方了，我最后用的是另外一个大佬的efi

**Comment by liweidong1216** [comment]
> > 顶配，4K同样也无法安装，也是卡在第二次启动的时候苹果LOGO处，CPU风扇狂转，只能强行关机~
> 
> 可能是大佬忘记改某些地方了，我最后用的是另外一个大佬的
最后用的那个EFI，麻烦告知一下

**Comment by liweidong1216** [comment]
最后用的那个EFI,麻烦告知一下

**Comment by roobtyan** [comment]
> 最后用的那个EFI,麻烦告知一下

https://github.com/goofysun/y9000x-4k-macos
这个，貌似没啥问题，
