### ISSUE TITLE
求助

### ISSUE THREAD

**Issue by zangling** [WangRicky/Y9000X-HACKINTOSH#70]
您好。我用的您的efi，我自己是 I9 的cpu ，使用了 mac pro 16，1 的机型，但是在“关于本机”中处理器的显示还是 i7 ，其他工具显示是 i9，清问是哪个地方写死了吗？

**Comment by JarvisXWL** [comment]
https://www.sqlsec.com/2018/09/cpu.html
这个不是随便改的吗？
