### ISSUE TITLE
1080p睡眠唤醒死机

### ISSUE THREAD

**Issue by liuzhaobo1999** [WangRicky/Y9000X-HACKINTOSH#72]
### 基本情况：

- i7-32G-1T-FHD，从10.15.7升级到11.2.3最新版本，一路顺畅。

### 解决的问题：

- intel-WiFi，在EFI添加了itlwm的驱动解决。

- 开机图标大的问题，修改EFI里面UIScale的值01（代码里面AQ==）解决。

### 待解决问题：

- 10.15.7睡眠唤醒是好的

- 因为是FHD屏幕，按照之前的方案是将4k补丁整个删除PciRoot(0x0)/Pci(0x2,0x0)，但是删除后开机黑屏。

- 不删除4k补丁，睡眠唤醒黑屏，看前面大佬的方案，修改EFI里面dpcd-max-link-rate的值0A00000（代码里面CgAAAA==），这样确实唤醒后会亮屏，但是亮屏后键盘、触摸板、鼠标都没反应，只能强制关机。
- 想问下大佬这个怎么解决？

**Comment by yujiaze00** [comment]
我的貌似偶尔这样，有时候睡一晚上没事，有时候中午打开盖子风扇在转，但屏幕没反应

**Comment by StarMoonCity** [comment]
> ### 基本情况：
> * i7-32G-1T-FHD，从10.15.7升级到11.2.3最新版本，一路顺畅。
> 
> ### 解决的问题：
> * intel-WiFi，在EFI添加了itlwm的驱动解决。
> * 开机图标大的问题，修改EFI里面UIScale的值01（代码里面AQ==）解决。
> 
> ### 待解决问题：
> * 10.15.7睡眠唤醒是好的
> * 因为是FHD屏幕，按照之前的方案是将4k补丁整个删除PciRoot(0x0)/Pci(0x2,0x0)，但是删除后开机黑屏。
> * 不删除4k补丁，睡眠唤醒黑屏，看前面大佬的方案，修改EFI里面dpcd-max-link-rate的值0A00000（代码里面CgAAAA==），这样确实唤醒后会亮屏，但是亮屏后键盘、触摸板、鼠标都没反应，只能强制关机。
> * 想问下大佬这个怎么解决？

hibernationFixup.kext试一下这个

**Comment by liuzhaobo1999** [comment]
@sjfhd 加载了hibernationFixup.kext这个还是一样, 睡眠唤醒后头两三秒好的, 之后就卡死了, 鼠标键盘都没反应.
@Sulisong 谢谢, 按照里面PowerTimeoutKernelPanic勾上, 可以了.
@yujiaze00 如果和我的问题一样, 可以按照这个来设置: [解锁会假死](https://github.com/WangRicky/Y9000X-HACKINTOSH/issues/60).
