### ISSUE TITLE
请问怎么屏蔽第二盘位？

### ISSUE THREAD

**Issue by playersun** [WangRicky/Y9000X-HACKINTOSH#74]
您好，我的win10系统装在了第二盘位，就是S位靠近电源的那块。第一盘位用的是WD sn750，请问要怎么修改才能屏蔽第二盘位的pm981a？

**Comment by WangRicky** [comment]
修改SSDT-DNVMe中RP09为RP21

**Comment by WangRicky** [comment]
> 您好，我的win10系统装在了第二盘位，就是S位靠近电源的那块。第一盘位用的是WD sn750，请问要怎么修改才能屏蔽第二盘位的pm981a？

修改SSDT-DNVMe中RP09为RP21

**Comment by techorie-admin** [comment]
> > 您好，我的win10系统装在了第二盘位，就是S位靠近电源的那块。第一盘位用的是WD sn750，请问要怎么修改才能屏蔽第二盘位的pm981a？
> 
> 修改SSDT-DNVMe中RP09为RP21

您好，请问opencore可以在windows里面修改吗？没有改过，请问有什么方法可以修改？

**Comment by playersun** [comment]
> > 您好，我的win10系统装在了第二盘位，就是S位靠近电源的那块。第一盘位用的是WD sn750，请问要怎么修改才能屏蔽第二盘位的pm981a？
> 
> 修改SSDT-DNVMe中RP09为RP21

您好，请问SSDT-DNVMe可以在windows10 中修改吗？没有弄过不知道怎么修改。

**Comment by JarvisXWL** [comment]
> > > 您好，我的win10系统装在了第二盘位，就是S位靠近电源的那块。第一盘位用的是WD sn750，请问要怎么修改才能屏蔽第二盘位的pm981a？
> > 
> > 
> > 修改SSDT-DNVMe中RP09为RP21
> 
> 您好，请问SSDT-DNVMe可以在windows10 中修改吗？没有弄过不知道怎么修改。

不要想了 装个苹果虚拟机会方便很多
