### ISSUE TITLE
请问大家外接屏幕是否能达到4K@60Hz，我只能达到30Hz

### ISSUE THREAD

**Issue by Fordisk123** [WangRicky/Y9000X-HACKINTOSH#76]
我之前黑过小新pro13，外接4K@60Hz的屏幕是OK的，显卡都是同样的UHD 630，用的同样的线材，同样的显示器。

**Comment by hx2nn** [comment]
如果你用的扩展坞然后hdmi连接显示器，基本上无法实现（可以实现的扩展坞上千了）。你可以试试typec转dp线连接显示器就可以了

**Comment by jingyu-tong** [comment]
typec转dp亲测可以，拓展坞可能hdmi2.0的可以

**Comment by Fordisk123** [comment]
> typec转dp亲测可以，拓展坞可能hdmi2.0的可以

嗯 我有2个typec线，一个是typec转hdmi2.0 一个是typec转dp  2个线在小新pro13上都可以实现4K@60Hz，在Y9000X上 typeC转HDMI不行，typec转DP可以
