### ISSUE TITLE
请问是否有主板原理图，本人想解决一下扬声器问题

### ISSUE THREAD

**Issue by qsazx874** [WangRicky/Y9000X-HACKINTOSH#82]
如果有原理图，我想可以搞定

**Comment by Sulisong** [comment]
> 如果有原理图，我想可以搞定

https://github.com/Corazon0513/VoodooI2CTAS2770
可以看一下这个项目

**Comment by StarMoonCity** [comment]
看一下这个
https://club.lenovo.com.cn/thread-7817162-1-1.html

**Comment by WangRicky** [comment]
#91
