### ISSUE TITLE
开机大概率黑屏

### ISSUE THREAD

**Issue by ImKujio** [WangRicky/Y9000X-HACKINTOSH#83]
如题
开机进度条1/3处黑屏，只有很少时候可以正常进系统，黑屏时有背光脸盘灯亮有风扇声,黑屏后盒盖可以进入睡眠，之后开盖是可以正常唤醒的。
三码正常
![image](https://user-images.githubusercontent.com/18486297/123422381-b4602800-d5f0-11eb-99b3-e38ebceb5f29.png)
显卡地址也删了
![image](https://user-images.githubusercontent.com/18486297/123422683-2173bd80-d5f1-11eb-8d43-cef666b05d0b.png)
通通没有用！！！！
最后自己使用0x 3E9B0000/3E9B0006/3E9B0007/3E9B0009/生成补丁其中3E9B0007花屏，其他的还是会黑屏。
这个问题我以前的oc没有问题但是我因为要换回ax200网卡，我的oc版本太低所以只好升oc，自己手动升级也是这个问题，用了wangricky的也是这个问题，找了好几天方法了，要么没说清楚要么没用。
我猜问题因该不是出在以上这些地方，可能是其他配置影响导致的，我不会开启动调试，据说要替换debug版oc有些麻烦，如果还是没有解决，我再考虑debug
最后：我是i5版的

**Comment by brucemeteor** [comment]
开机使用debug模式的话，可以在EFI中找到config.plist文件，
在这个位置内，增加 空格，然后添加-v即可。
https://github.com/WangRicky/Y9000X-HACKINTOSH/blob/4a5ae304a2ea95339552fdd31ae25eff780d688b/EFI/OC/config.plist#L1187

**Comment by brucemeteor** [comment]
版本： Catalina 15.7
引导方式：OC
问题描述：黑苹果安装过程没有问题，正常安装，启动后除了无线网和蓝牙，其他功能全部正常，
但是，每次启动时，大概率卡在白苹果logo界面大约2/3处，使用了-v模式输出日志后，发现每次卡住的位置都是相同的一个地方。有一定开率启动后会直接进入系统。目前原因不详
环境描述：
1. 已经按照教程生成了三码，并且保存。
2. 目前已经安装成功系统
3. 笔记本型号是 y9000x 2020版本，4K分辨率，I7-9750h处理器

问题报错：
** In memory penic Stackshot Successed ** Bytes Traced 2627824 **
Mrlting local cores ... 100..Recorded panic stackshot in corefile at offset 0x7000,compressed to 82606 bytes
Beginning coredump of kernel
10..
20..
30..
....
90..
100.. done
Coredump complete of kernel,dumped 596 segments (655278080 bytes), 1 threads(184bytes) overall uncompress...........
 please go to https //panic.apple.com to report this panic


问题猜测：
1. 无线网卡使用的是原装的AX200
2. SSD并没有拆卸，而是新增加了一个SSD，新增加的SSD型号是HP EX950 1T版本
3. 我并没有定制USB接口，因为在网上看USB接口影响的原因只是速度不满，我暂时没有需求，就没有定制，也许是定制USB的问题？？
4. 
5.

**Comment by ImKujio** [comment]
@laureler 我的SSD拆了，用的三星970evo，USB我之前一直用的我自己定制，手动升级到OC0.7之后也是黑屏问题，之后才使用的WangRicky的这个。所以应该与SSD和USB没关系。

**Comment by Orion-sky** [comment]
你这个问题现在解决了吗，我也是i5，但是升级了4K屏，1080P的时候一切正常，升级了4K屏后，就出现了和你一样的情况

**Comment by jingyu-tong** [comment]
> 你这个问题现在解决了吗，我也是i5，但是升级了4K屏，1080P的时候一切正常，升级了4K屏后，就出现了和你一样的情况

你1080p怎么升级的4k屏？

**Comment by ImKujio** [comment]
> 你1080p怎么升级的4k屏？

解决了,是OC升级后SSDT-PNLF-CFL这个补丁的启动参数变了,
![image](https://user-images.githubusercontent.com/18486297/143366289-106b1d5c-dd87-4c49-9142-44d605291633.png)
启动参数加上这个就好了

**Comment by ImKujio** [comment]
> > 你这个问题现在解决了吗，我也是i5，但是升级了4K屏，1080P的时候一切正常，升级了4K屏后，就出现了和你一样的情况
> 
> 你1080p怎么升级的4k屏？

还有我没升级4k啊,我用的也是这个EFI,自己调了一下,1080p,i5的

**Comment by ImKujio** [comment]
> 你这个问题现在解决了吗，我也是i5，但是升级了4K屏，1080P的时候一切正常，升级了4K屏后，就出现了和你一样的情况

解决了,看楼上

**Comment by zorroye** [comment]
1080p的配置发一下看看，我也是这个情况
