### ISSUE TITLE
在联想社区看到 linux 外放问题解决了，黑苹果能参考吗

### ISSUE THREAD

**Issue by StarMoonCity** [WangRicky/Y9000X-HACKINTOSH#88]
原文地址
https://club.lenovo.com.cn/thread-7817162-1-1.html
## 解决方法
在/lib/firmware/目录下新建一个文件legion-alc285-0.0.1.patch
在/etc/modprobe.d/目录下新建文件legion-alc285-0.0.1.conf
[legion_alc285.zip](https://github.com/WangRicky/Y9000X-HACKINTOSH/files/7400036/legion_alc285.zip)

**Comment by zorroye** [comment]
666，，看来也不远了吧。。。

**Comment by Sulisong** [comment]
> 666，，看来也不远了吧。。。

可以了，用这个教程：https://gitee.com/YasuStudio/fix-speaker-y9000x

**Comment by StarMoonCity** [comment]
> > 666，，看来也不远了吧。。。
> 
> 可以了，用这个教程：https://gitee.com/YasuStudio/fix-speaker-y9000x
感谢！！！ 我去试试
