### ISSUE TITLE
Monterey 搜索不到蓝牙列表

### ISSUE THREAD

**Issue by peakliuz** [WangRicky/Y9000X-HACKINTOSH#89]
- commitId: 2b1a412a2636f4d135f99663e1bf4615eb65516f
 - 现象: 蓝牙可正常打开关闭,但是搜索不到蓝牙列表
 - 系统: mac 12 Monterey 
 - 蓝牙设备: dw1820a
 - 设备信息: 9750H 4k

**Comment by zorroye** [comment]
这个好像是普遍问题吧。。
