### ISSUE TITLE
外放无法解决的根本原因

### ISSUE THREAD

**Issue by hx2nn** [WangRicky/Y9000X-HACKINTOSH#9]
在微博中给凤凰留言得到的答复，应该是问题所在：
其他系统没有外放应该是Smart Amplifier导致的，由2TI的TAS2770RJQR芯片组成，外放都要经过这个。

**Comment by WangRicky** [comment]
这个放大器我在TI的官网上看到了Linux驱动的相关资料，不过型号是TAS2770，现在看情况不是BIOS的选项可以解决的了，大概率外放要凉，PC厂商几乎没有对其他操作系统做驱动先例

**Comment by ihipop** [comment]
TAS2770的驱动好像很早就进内核了，TAS2770RJQR看起来像子系列芯片，会不会只是设备ID不同

**Comment by ihipop** [comment]
我编译了5.5内核集成的TAS2770驱动，加载了，没用，还是没声音
![image](https://user-images.githubusercontent.com/423077/85248406-48019480-b483-11ea-80b3-1018c4e4abcf.png)
https://github.com/torvalds/linux/blob/v5.5/sound/soc/codecs/Makefile#L202 

https://github.com/torvalds/linux/blob/v5.5/sound/soc/codecs/tas2770.c

**Comment by ihipop** [comment]
@hx2nn 请问楼主说的凤凰是谁啊? @WangRicky

**Comment by Corazon0513** [comment]
> 我编译了5.5内核集成的TAS2770驱动，加载了，没用，还是没声音
> 
> ![image](https://user-images.githubusercontent.com/423077/85248406-48019480-b483-11ea-80b3-1018c4e4abcf.png)
> 
> https://github.com/torvalds/linux/blob/v5.5/sound/soc/codecs/Makefile#L202 
> 
> 
> 
> https://github.com/torvalds/linux/blob/v5.5/sound/soc/codecs/tas2770.c


https://github.com/Corazon0513/VoodooI2CTAS2770/issues/1#issuecomment-647082366

**Comment by ihipop** [comment]
@Corazon0513 已star关注
