### ISSUE TITLE
带独显的2021款Y9000X能用吗？

### ISSUE THREAD

**Issue by gzjaychen** [WangRicky/Y9000X-HACKINTOSH#90]
2021款带独显，10875H。
在不需要驱动独显的情况下，请问是否支持呢？

**Comment by xiaoMGitHub** [comment]
> 2021款带独显，10875H。 在不需要驱动独显的情况下，请问是否支持呢？

请问你试过安装吗，我进不了安装界面

**Comment by gzjaychen** [comment]
> > 2021款带独显，10875H。 在不需要驱动独显的情况下，请问是否支持呢？
> 
> 请问你试过安装吗，我进不了安装界面

我没有机器，先咨询是否支持，支持再考虑购入。

**Comment by xiaoMGitHub** [comment]
> > > 2021款带独显，10875H。 在不需要驱动独显的情况下，请问是否支持呢？
> > 
> > 
> > 请问你试过安装吗，我进不了安装界面
> 
> 我没有机器，先咨询是否支持，支持再考虑购入。

完美了，感谢WangRicky大佬的EFI

**Comment by gzjaychen** [comment]
> > > > 2021款带独显，10875H。 在不需要驱动独显的情况下，请问是否支持呢？
> > > 
> > > 
> > > 请问你试过安装吗，我进不了安装界面
> > 
> > 
> > 我没有机器，先咨询是否支持，支持再考虑购入。
> 
> 完美了，感谢WangRicky大佬的EFI

那是可用的意思吗？
