### ISSUE TITLE
请教下。安装了您最新的版本，蓝牙无法使用。

### ISSUE THREAD

**Issue by zangling** [WangRicky/Y9000X-HACKINTOSH#93]
I9的机器。
声音十分完美，就是蓝牙有问题。无法打开。始终用不了。
网卡是 1820a 。网卡没问题，很正常。

还有一个就是重启后外放还是没有，需要跑一次那个脚本，是正常的对吧？

机型根据cpu 修改成 16，1  其他就没有区别了应该。

**Comment by HiramChen-CN** [comment]
他这个进行了USB定制，定制为mbp16,4，所以其他机型的内置USB会识别不出来，要么改定制的USB内核扩展，要么换成mbp16,4型号

**Comment by zangling** [comment]
明白了。就只能选16，4 了。USB 定制不会啊。。。

**Comment by zangling** [comment]
换成 16，4 了，能打开蓝牙，在系统报告中能看到蓝牙设备，但是搜不到任何蓝牙。

===============================================================
  蓝牙控制器：
  地址：	C8:FF:28:78:C0:86
  状态：	打开
  芯片组：	THIRD_PARTY_DONGLE
  可被发现：	打开
  固件版本：	v26119 c4096
  产品ID：	0x0001
  支持的服务：	0x382039 < HFP AVRCP A2DP HID Braille AACP GATT Serial >
  传输：	USB
  供应商ID：	0x004C (Apple)

**Comment by zorroye** [comment]
用原版efi，重启后看不到菜单是啥问题？。。。

**Comment by WangRicky** [comment]
已更新解决
