### ISSUE TITLE
OC引导Windows10/11，报ACPI_BIOS_ERROR的错误码

### ISSUE THREAD

**Issue by Venus-Chen** [WangRicky/Y9000X-HACKINTOSH#96]
我的电脑里面是双硬盘双系统，之前的EFI是基于OC 0.7.0版本的，开机后可以正常引导Windows10/11，但是当我替换了此EFI后，可以正常引导MacOS，但是在引导Windows的时候，就会蓝屏报错，报ACPI_BIOS_ERROR的错误码。
我查看了已有的问题里面，按照wghemail 的方法，尝试修改 “SSDT-XOSI.aml” 文件和 “SSDT-TB3.aml” 文件里面的内容，添加 “If (_OSI ("Darwin"))” 判断和修改 “If ( OSDW()) 替换为If (_OSI ("Darwin"))” 后，均没有解决问题，还是会报这个错误。

**Comment by WangRicky** [comment]
本配置不支持oc引导win
